// Phase 1: Hardcoded resources for demo/MVP
// Phase 2: Replace with Supabase queries

export const DEMO_RESOURCES = [
  // === FINANCIAL ===
  {
    id: 'dla-children',
    category: 'financial',
    type: 'benefit',
    conditionCategory: 'all',
    title: 'Disability Living Allowance (DLA) for Children',
    organisation: 'Department for Work and Pensions',
    description: 'Tax-free benefit for children under 16 with a health condition or disability. Worth up to \u00A3187.45/week at the highest rate. Special fast-track rules for terminal illness.',
    eligibility_summary: 'Children under 16 who need more help or supervision than a child of the same age without a disability.',
    max_award_gbp: 9748,
    how_to_apply: 'Call the DLA helpline on 0800 121 4600 or download the form from gov.uk. Ask your hospital social worker for help completing it \u2014 they do this regularly.',
    apply_url: 'https://www.gov.uk/disability-living-allowance-children',
    apply_phone: '0800 121 4600',
    turnaround_days: 40,
  },
  {
    id: 'carers-allowance',
    category: 'financial',
    type: 'benefit',
    conditionCategory: 'all',
    title: "Carer's Allowance",
    organisation: 'Department for Work and Pensions',
    description: "\u00A381.90/week for anyone spending 35+ hours a week caring for a child who gets middle or highest rate DLA care component. You don't need to be related to the child.",
    eligibility_summary: "You care for someone 35+ hours/week, earn under \u00A3151/week (after deductions), and you're 16 or over.",
    max_award_gbp: 4259,
    how_to_apply: "Apply online at gov.uk. You'll need your National Insurance number and the child's DLA reference number.",
    apply_url: 'https://www.gov.uk/carers-allowance',
    apply_phone: '0800 731 0297',
    turnaround_days: 28,
  },
  {
    id: 'family-fund',
    category: 'financial',
    type: 'grant',
    conditionCategory: 'all',
    title: 'Family Fund Grant',
    organisation: 'Family Fund',
    description: 'Grants for essential items: washing machines, computers, hospital visiting costs, family breaks, clothing, and bedding. For families on low incomes raising a disabled or seriously ill child.',
    eligibility_summary: 'Families in the UK with a severely disabled or seriously ill child (under 18), on a low income or receiving certain benefits.',
    max_award_gbp: 2000,
    how_to_apply: "Apply online. You'll need a letter from your child's consultant confirming the diagnosis.",
    apply_url: 'https://www.familyfund.org.uk/apply',
    apply_phone: '01904 550055',
    turnaround_days: 42,
  },
  {
    id: 'react-charity',
    category: 'financial',
    type: 'emergency_fund',
    conditionCategory: 'all',
    title: 'REACT Emergency Grants',
    organisation: 'REACT (Rapid Effective Assistance for Children with Potentially Terminal Illness)',
    description: 'Emergency grants for specialist equipment, domestic appliances, educational equipment, holidays, and funeral expenses. Responds within 48 hours.',
    eligibility_summary: 'Children with a life-limiting illness in financially disadvantaged households.',
    how_to_apply: 'Referral required from a health professional, social worker, or charity. They can call or email on your behalf.',
    apply_url: 'https://reactcharity.org/apply',
    apply_phone: '020 8940 2575',
    turnaround_days: 2,
  },
  {
    id: 'ylvc-grant',
    category: 'financial',
    type: 'grant',
    conditionCategory: 'cancer',
    title: 'Young Lives vs Cancer Financial Support',
    organisation: 'Young Lives vs Cancer',
    description: 'Registration grants (\u00A3100), crisis grants, and ongoing financial support for families of children and young people (0-25) with cancer. Also provides free accommodation near treatment centres.',
    eligibility_summary: 'Families of children/young people aged 0-25 diagnosed with cancer in the UK.',
    max_award_gbp: 500,
    how_to_apply: 'Contact their support team. A social worker at your treatment centre can also refer you.',
    apply_url: 'https://www.younglivesvscancer.org.uk/what-we-do/the-six-ways-we-help/',
    apply_phone: '0800 012 1020',
    turnaround_days: 7,
  },
  {
    id: 'htcs',
    category: 'financial',
    type: 'benefit',
    conditionCategory: 'all',
    title: 'Healthcare Travel Costs Scheme',
    organisation: 'NHS',
    description: "Get your travel costs to hospital refunded if you're on a low income or receiving qualifying benefits. Covers public transport, mileage, parking, and sometimes taxis.",
    eligibility_summary: 'Patients/families on qualifying benefits (UC, Income Support, ESA) or low income. Must have a referral for specialist care.',
    how_to_apply: "Claim at the hospital cashier's office after each appointment. Keep all receipts. Claim within 3 months.",
    apply_url: 'https://www.nhs.uk/nhs-services/help-with-health-costs/healthcare-travel-costs-scheme-htcs/',
    turnaround_days: 1,
  },

  // === MEDICAL ===
  {
    id: 'cclg-ptc',
    category: 'medical',
    type: 'hospital',
    conditionCategory: 'cancer',
    title: 'Find Your Principal Treatment Centre',
    organisation: "Children's Cancer and Leukaemia Group (CCLG)",
    description: "The UK has 19 Principal Treatment Centres (PTCs) that specialise in children's cancer. Your child will be referred to the nearest one. They coordinate all treatment including shared care with your local hospital.",
    eligibility_summary: 'All children diagnosed with cancer are referred to their regional PTC.',
    how_to_apply: 'Your GP or local hospital will refer you. If you need to check which PTC covers your area, call CCLG.',
    apply_url: 'https://www.cclg.org.uk/young-people-and-cancer/i-have-cancer/hospitals/principal-treatment-centres',
    apply_phone: '0116 252 5858',
  },
  {
    id: 'chf-specialist',
    category: 'medical',
    type: 'specialist_service',
    conditionCategory: 'heart',
    title: "Children's Heart Federation Support",
    organisation: "Children's Heart Federation",
    description: 'Information and support for families of children with heart conditions. Can help you understand your child\'s diagnosis, treatment options, and connect you with other families.',
    eligibility_summary: 'Any family with a child with a congenital or acquired heart condition.',
    how_to_apply: 'Contact their helpline or browse their condition-specific information pages.',
    apply_url: 'https://www.chfed.org.uk/',
    apply_phone: '0808 808 5000',
  },

  // === EMOTIONAL ===
  {
    id: 'together-helpline',
    category: 'emotional',
    type: 'helpline',
    conditionCategory: 'all',
    title: 'Together for Short Lives Helpline',
    organisation: 'Together for Short Lives',
    description: 'Free helpline for families of children with life-limiting or life-threatening conditions. Can help you find local services, support groups, and answer questions about your rights and entitlements.',
    eligibility_summary: 'Any family with a child (0-18) with a life-limiting or life-threatening condition.',
    how_to_apply: 'Call the helpline. Open Monday to Friday, 9am-5pm.',
    apply_phone: '0808 8088 100',
    apply_url: 'https://www.togetherforshortlives.org.uk/get-support/',
  },
  {
    id: 'rainbow-trust',
    category: 'emotional',
    type: 'support_group',
    conditionCategory: 'all',
    title: 'Rainbow Trust Family Support Workers',
    organisation: 'Rainbow Trust Children\'s Charity',
    description: 'A dedicated Family Support Worker provides ongoing practical and emotional support. They can accompany you to hospital appointments, look after siblings, and be there when you need someone.',
    eligibility_summary: 'Families with a child aged 0-18 with a life-threatening or terminal illness, in areas where Rainbow Trust operates (9 teams across UK).',
    how_to_apply: 'Self-refer via their website or ask your hospital social worker to refer you.',
    apply_url: 'https://www.rainbowtrust.org.uk/support',
    apply_phone: '01372 220000',
  },
  {
    id: 'macmillan-line',
    category: 'emotional',
    type: 'helpline',
    conditionCategory: 'cancer',
    title: 'Macmillan Support Line',
    organisation: 'Macmillan Cancer Support',
    description: 'Free, confidential support from cancer specialists. They can help with medical questions, emotional support, financial guidance, and practical concerns. Open 7 days a week.',
    eligibility_summary: 'Anyone affected by cancer, including parents of children with cancer.',
    how_to_apply: 'Call or use the online chat. No referral needed.',
    apply_phone: '0808 808 0000',
    apply_url: 'https://www.macmillan.org.uk/cancer-information-and-support/get-help',
  },
  {
    id: 'sibs-support',
    category: 'emotional',
    type: 'support_group',
    conditionCategory: 'all',
    title: 'Sibs \u2014 Support for Siblings',
    organisation: 'Sibs',
    description: "Support specifically for brothers and sisters of seriously ill children. Online groups, information, and workshops to help siblings cope with their feelings and experiences.",
    eligibility_summary: 'Siblings of any age whose brother or sister has a disability, chronic illness, or life-limiting condition.',
    apply_url: 'https://www.sibs.org.uk/',
  },

  // === PRACTICAL ===
  {
    id: 'rmh',
    category: 'practical',
    type: 'accommodation',
    conditionCategory: 'all',
    title: 'Ronald McDonald House \u2014 Free Accommodation',
    organisation: 'Ronald McDonald House Charities UK',
    description: "14 free Houses near major children's hospitals across the UK. Families stay for free while their child is in hospital. Includes kitchen, laundry, and play areas. The Alder Hey House has 84 bedrooms.",
    eligibility_summary: 'Families with a child being treated at a partnered NHS hospital. Referral from the hospital is usually needed.',
    how_to_apply: "Ask your child's ward nurse or hospital social worker to refer you. Some Houses accept self-referral.",
    apply_url: 'https://rmhc.org.uk/our-houses/',
    apply_phone: '020 7462 4800',
  },
  {
    id: 'make-a-wish',
    category: 'practical',
    type: 'other',
    conditionCategory: 'all',
    title: 'Make-A-Wish UK',
    organisation: 'Make-A-Wish UK',
    description: "Grants wishes for children aged 3-17 with life-threatening conditions. Wishes can be anything: meeting a hero, going on a trip, having a bedroom makeover, or getting a special experience.",
    eligibility_summary: 'Children aged 3-17 with a life-threatening condition. Medical referral required.',
    how_to_apply: "Referral from a medical professional (consultant, clinical nurse specialist, or social worker). They'll confirm the child's eligibility.",
    apply_url: 'https://www.make-a-wish.org.uk/refer-a-child/',
    apply_phone: '01276 405060',
  },
  {
    id: 'starlight',
    category: 'practical',
    type: 'other',
    conditionCategory: 'all',
    title: 'Starlight Children\u2019s Foundation',
    organisation: "Starlight Children's Foundation",
    description: 'Provides entertainment and play equipment to hospitals, grants wishes for seriously ill children, and offers sensory toys and Distraction Boxes for hospital stays.',
    eligibility_summary: 'Seriously ill children aged 4-18. Wish referral from a medical professional.',
    apply_url: 'https://www.starlight.org.uk/',
    apply_phone: '020 7262 2881',
  },
  {
    id: 'wellchild',
    category: 'practical',
    type: 'other',
    conditionCategory: 'all',
    title: 'WellChild Support',
    organisation: 'WellChild',
    description: 'WellChild Nurses provide support at home, helping coordinate care and reducing hospital visits. They also offer home and garden transformations for families with seriously ill children.',
    eligibility_summary: 'Children with serious or complex health conditions across the UK.',
    apply_url: 'https://www.wellchild.org.uk/',
    apply_phone: '01242 530007',
  },

  // === MENTAL HEALTH ===
  {
    id: 'youngminds-helpline',
    category: 'emotional',
    type: 'helpline',
    conditionCategory: 'mental_health',
    title: 'YoungMinds Parents Helpline',
    organisation: 'YoungMinds',
    description: 'Free, confidential helpline for parents worried about their child\'s mental health. Trained advisers can talk through your concerns and help you work out the best next steps, whether your child is struggling with anxiety, self-harm, bullying, or anything else.',
    eligibility_summary: 'Any parent or carer of a child or young person up to age 25.',
    how_to_apply: 'Call the helpline or use the online chat. No referral needed. Open Mon, Thu, Fri 9.30am-4pm and Tue, Wed 9.30am-6pm.',
    apply_url: 'https://www.youngminds.org.uk/parent/parents-helpline/',
    apply_phone: '0808 802 5544',
  },
  {
    id: 'camhs-referral',
    category: 'medical',
    type: 'specialist_service',
    conditionCategory: 'mental_health',
    title: 'CAMHS \u2014 How to Get a Referral',
    organisation: 'NHS',
    description: 'CAMHS (Child and Adolescent Mental Health Services) is the NHS service for children and young people struggling with their mental health. Referrals can come from your GP, school, or in many areas you can self-refer. Waiting times vary by area.',
    eligibility_summary: 'Children and young people up to age 18 with mental health difficulties that need specialist support.',
    how_to_apply: 'Ask your GP for a referral, or check your local CAMHS website to see if they accept self-referrals. Your child\'s school can also refer.',
    apply_url: 'https://www.nhs.uk/mental-health/nhs-voluntary-charity-services/nhs-services/children-young-people-mental-health-services-cypmhs/',
  },
  {
    id: 'kooth-counselling',
    category: 'emotional',
    type: 'helpline',
    conditionCategory: 'mental_health',
    title: 'Kooth Online Counselling',
    organisation: 'Kooth',
    description: 'Free, anonymous online counselling and emotional wellbeing support for young people aged 10-25. No referral or waiting list. Your child can chat with a qualified counsellor via text, join moderated forums, or use self-help tools, all from their phone or laptop.',
    eligibility_summary: 'Young people aged 10-25. Free and anonymous, no GP referral needed.',
    how_to_apply: 'Your child can sign up at kooth.com using just a nickname. No personal details needed. Available every day of the year.',
    apply_url: 'https://www.kooth.com/',
  },
  {
    id: 'place2be',
    category: 'emotional',
    type: 'support_group',
    conditionCategory: 'mental_health',
    title: 'Place2Be School Counselling',
    organisation: 'Place2Be',
    description: 'Place2Be provides in-school counselling and mental health support in over 500 primary and secondary schools across England, Scotland and Wales. Children can drop in for a chat or be referred for one-to-one counselling by their teacher.',
    eligibility_summary: 'Children at schools that partner with Place2Be. Check their website to see if your school is covered.',
    how_to_apply: 'Ask your child\'s school if they work with Place2Be, or visit the website to find out which schools are partnered.',
    apply_url: 'https://www.place2be.org.uk/our-services/',
  },

  // === DEVELOPMENTAL / AUTISM ===
  {
    id: 'nas-helpline',
    category: 'emotional',
    type: 'helpline',
    conditionCategory: 'developmental',
    title: 'National Autistic Society Helpline',
    organisation: 'National Autistic Society',
    description: 'Free helpline for autistic people, their families, and anyone who works with them. They can help you understand a diagnosis, find local services, navigate school issues, or just talk through what you\'re going through.',
    eligibility_summary: 'Anyone affected by autism, including parents awaiting or following a diagnosis.',
    how_to_apply: 'Call the helpline Mon-Thu 10am-4pm, Fri 9am-3pm. No referral needed.',
    apply_url: 'https://www.autism.org.uk/advice-and-guidance/help-and-support',
    apply_phone: '0808 800 4104',
  },
  {
    id: 'ambitious-autism',
    category: 'practical',
    type: 'other',
    conditionCategory: 'developmental',
    title: 'Ambitious About Autism',
    organisation: 'Ambitious about Autism',
    description: 'National charity offering education, support and advocacy for autistic children and young people. They run specialist schools, an online youth network, and campaigns for better understanding and support for autistic young people.',
    eligibility_summary: 'Autistic children and young people and their families across the UK.',
    how_to_apply: 'Visit their website for resources, or call to find out about schools and programmes.',
    apply_url: 'https://www.ambitiousaboutautism.org.uk/',
    apply_phone: '020 8815 5444',
  },
  {
    id: 'adhd-foundation',
    category: 'emotional',
    type: 'support_group',
    conditionCategory: 'developmental',
    title: 'ADHD Foundation',
    organisation: 'ADHD Foundation',
    description: 'The UK\'s leading ADHD and neurodiversity charity. They offer parent workshops, training for schools, assessments, and a wealth of free resources to help families understand and manage ADHD day to day.',
    eligibility_summary: 'Families, children and young people affected by ADHD or other neurodevelopmental conditions.',
    how_to_apply: 'Call or visit the website for information about services in your area. Open Mon-Fri 9am-5pm.',
    apply_url: 'https://www.adhdfoundation.org.uk/',
    apply_phone: '0151 541 9020',
  },
  {
    id: 'cerebra-grants',
    category: 'financial',
    type: 'grant',
    conditionCategory: 'developmental',
    title: 'Cerebra Grants',
    organisation: 'Cerebra',
    description: 'Cerebra helps families with children who have brain conditions, offering free discovery library toys, sleep advice, legal rights guidance, and innovation support including custom equipment design. They work with families to find practical solutions.',
    eligibility_summary: 'Families with a child who has a brain-related condition, including autism, epilepsy, and genetic conditions.',
    max_award_gbp: 500,
    how_to_apply: 'Contact Cerebra to discuss your needs. They can help with a range of support from lending specialist toys to designing bespoke equipment.',
    apply_url: 'https://cerebra.org.uk/what-we-do/',
    apply_phone: '01267 244200',
  },

  // === SENSORY / COMMUNICATION ===
  {
    id: 'smira-support',
    category: 'emotional',
    type: 'support_group',
    conditionCategory: 'sensory',
    title: 'SMIRA \u2014 Selective Mutism Support',
    organisation: 'Selective Mutism Information & Research Association',
    description: 'The UK\'s leading charity for selective mutism, supporting families since 1992. They offer parent support groups, free downloadable resources, and practical guidance on helping your child communicate. A lifeline if your child speaks freely at home but goes silent in other settings.',
    eligibility_summary: 'Anyone affected by selective mutism, including parents, young people, and professionals.',
    how_to_apply: 'Visit the website for resources and information, or call the helpline.',
    apply_url: 'https://www.selectivemutism.org.uk/',
    apply_phone: '0800 228 9765',
  },
  {
    id: 'speech-language-uk',
    category: 'medical',
    type: 'specialist_service',
    conditionCategory: 'sensory',
    title: 'I CAN / Speech and Language UK',
    organisation: 'I CAN (now Speech and Language UK)',
    description: 'Free enquiry service where you can speak directly to a speech and language therapist by phone or video call. They help parents understand speech and language delays, offer practical tips, and point you towards local services and support.',
    eligibility_summary: 'Any parent or carer concerned about a child\'s speech, language or communication development.',
    how_to_apply: 'Call the enquiry line or email to book a free call with a speech and language therapist.',
    apply_url: 'https://www.icancharity.org.uk/i-can-help/',
    apply_phone: '020 7843 2544',
  },
  {
    id: 'ndcs-support',
    category: 'practical',
    type: 'other',
    conditionCategory: 'sensory',
    title: 'National Deaf Children\'s Society (NDCS)',
    organisation: 'National Deaf Children\'s Society',
    description: 'Free, impartial support for families with deaf children. Their helpline offers guidance on everything from hearing aids and cochlear implants to education rights and benefits. They also run family events and have a technology test centre where you can try equipment.',
    eligibility_summary: 'Any family with a deaf child or young person, from newborn to 18.',
    how_to_apply: 'Call the freephone helpline Mon-Thu 9am-5pm, Fri 9am-12.30pm. No referral needed.',
    apply_url: 'https://www.ndcs.org.uk/',
    apply_phone: '0808 800 8880',
  },
  {
    id: 'rnib-children',
    category: 'practical',
    type: 'other',
    conditionCategory: 'sensory',
    title: 'RNIB Children\'s Services',
    organisation: 'RNIB (Royal National Institute of Blind People)',
    description: 'Support for families with blind and partially sighted children, including early years development advice, education support, technology guidance, and emotional support. Their helpline team can help with practical questions about daily life, school, and benefits.',
    eligibility_summary: 'Families with a child or young person with any level of sight loss.',
    how_to_apply: 'Call the helpline or visit the website. No referral needed.',
    apply_url: 'https://www.rnib.org.uk/',
    apply_phone: '0303 123 9999',
  },

  // === LEARNING ===
  {
    id: 'bda-helpline',
    category: 'education',
    type: 'helpline',
    conditionCategory: 'learning',
    title: 'British Dyslexia Association Helpline',
    organisation: 'British Dyslexia Association',
    description: 'Free, confidential helpline for anyone affected by dyslexia or dyscalculia. They can advise on getting an assessment, school support, workplace adjustments, and what to do if your child is struggling with reading or writing.',
    eligibility_summary: 'Anyone affected by dyslexia or dyscalculia in the UK, including parents and young people.',
    how_to_apply: 'Call the helpline (Tue 10am-1pm, Wed-Thu 1pm-3pm) or email. Free and confidential.',
    apply_url: 'https://www.bdadyslexia.org.uk/services/helpline',
    apply_phone: '0333 405 4567',
  },
  {
    id: 'mencap-helpline',
    category: 'practical',
    type: 'helpline',
    conditionCategory: 'learning',
    title: 'Mencap Learning Disability Helpline',
    organisation: 'Mencap',
    description: 'Free advice service for people with a learning disability and their families. They can help with education, benefits, housing, social care, and your rights. If you\'re not sure where to start or what your child is entitled to, Mencap is a good first call.',
    eligibility_summary: 'People with a learning disability and their families or carers across the UK.',
    how_to_apply: 'Call the freephone helpline Mon-Fri 9am-3pm, or email for a response within 5 working days.',
    apply_url: 'https://www.mencap.org.uk/advice-and-support/learning-disability-helpline',
    apply_phone: '0808 808 1111',
  },

  // === PHYSICAL ===
  {
    id: 'whizz-kidz',
    category: 'practical',
    type: 'other',
    conditionCategory: 'physical',
    title: 'Whizz-Kidz \u2014 Mobility Equipment for Children',
    organisation: 'Whizz-Kidz',
    description: 'The UK\'s leading charity for young wheelchair users. They provide custom wheelchairs and mobility equipment when the NHS can\'t, plus wheelchair skills training, youth clubs, and an employability programme to build independence and confidence.',
    eligibility_summary: 'Young wheelchair users up to age 25 with a permanent physical disability. Equipment applications may have a waiting list.',
    how_to_apply: 'Apply online through the website. A clinical assessment will determine the right equipment for your child.',
    apply_url: 'https://www.whizz-kidz.org.uk/apply/',
  },
  {
    id: 'scope-helpline',
    category: 'emotional',
    type: 'helpline',
    conditionCategory: 'physical',
    title: 'Scope Helpline',
    organisation: 'Scope',
    description: 'Free, independent advice for disabled people and their families. Scope can help with benefits, education, employment, and everyday challenges. Their advisers understand the system and can help you access what you\'re entitled to.',
    eligibility_summary: 'Any disabled person or family member across the UK.',
    how_to_apply: 'Call the freephone helpline Mon-Sat 8am-8pm, Sun 10am-6pm. No referral needed.',
    apply_url: 'https://www.scope.org.uk/helpline',
    apply_phone: '0808 800 3333',
  },

  // === CHRONIC ===
  {
    id: 'diabetes-uk',
    category: 'emotional',
    type: 'helpline',
    conditionCategory: 'chronic',
    title: 'Diabetes UK Family Support',
    organisation: 'Diabetes UK',
    description: 'Helpline staffed by trained advisers who understand the daily reality of managing a child\'s diabetes. They can answer medical questions, help with school management plans, connect you with local family groups, and offer emotional support for the whole family.',
    eligibility_summary: 'Anyone affected by diabetes, including parents of children with Type 1 or Type 2 diabetes.',
    how_to_apply: 'Call the helpline Mon-Fri 9am-6pm or email. No referral needed.',
    apply_url: 'https://www.diabetes.org.uk/support-for-you',
    apply_phone: '0345 123 2399',
  },
  {
    id: 'asthma-lung-uk',
    category: 'medical',
    type: 'helpline',
    conditionCategory: 'chronic',
    title: 'Asthma + Lung UK Helpline',
    organisation: 'Asthma + Lung UK',
    description: 'Speak to a respiratory nurse for free, confidential advice about your child\'s asthma or lung condition. They can help with medication questions, asthma action plans, managing triggers, and what to do in an emergency.',
    eligibility_summary: 'Anyone with a lung condition or their family, including parents of children with asthma.',
    how_to_apply: 'Call Mon-Fri 9am-5pm, or WhatsApp on 07378 606 728. You can also email for a response within 2 working days.',
    apply_url: 'https://www.asthmaandlung.org.uk/helpline',
    apply_phone: '0300 222 5800',
  },
  {
    id: 'crohns-colitis-uk',
    category: 'emotional',
    type: 'helpline',
    conditionCategory: 'chronic',
    title: "Crohn's & Colitis UK Helpline",
    organisation: "Crohn's & Colitis UK",
    description: 'Support and information for anyone affected by Crohn\'s disease or ulcerative colitis. Their helpline team can explain treatments, help with school or work accommodations, and connect you with others going through the same thing.',
    eligibility_summary: 'Anyone affected by Crohn\'s disease, ulcerative colitis, or other forms of IBD, including parents.',
    how_to_apply: 'Call Mon-Fri 10am-3pm, use live chat on the website, or email.',
    apply_url: 'https://www.crohnsandcolitis.org.uk/info-support/support-for-you/helpline-service',
    apply_phone: '0300 222 5700',
  },

  // === EDUCATION / SEN ===
  {
    id: 'ipsea-advice',
    category: 'education',
    type: 'helpline',
    conditionCategory: 'all',
    title: 'IPSEA \u2014 Free SEN Legal Advice',
    organisation: 'IPSEA (Independent Provider of Special Education Advice)',
    description: 'Free, independent legal advice on special educational needs. IPSEA can help you understand your child\'s rights, challenge decisions about EHCP provision, and prepare for SEND Tribunal appeals. Run by legal experts who know the system inside out.',
    eligibility_summary: 'Any parent or carer of a child or young person with SEN or a disability in England.',
    how_to_apply: 'Book a callback on the website, or call the helpline on Tue, Wed, or Fri 9.30am-2.30pm.',
    apply_url: 'https://www.ipsea.org.uk/advice-line',
    apply_phone: '0300 018 4016',
  },
  {
    id: 'contact-ehcp',
    category: 'education',
    type: 'helpline',
    conditionCategory: 'all',
    title: 'Contact \u2014 EHCP & SEN Advice',
    organisation: 'Contact',
    description: 'Free helpline for families of disabled children covering everything from EHCP applications to benefits, social care, and education rights. If you\'re feeling overwhelmed by paperwork and processes, Contact can talk you through your options step by step.',
    eligibility_summary: 'Parents and carers of disabled children from birth to age 25 across the UK.',
    how_to_apply: 'Call the freephone helpline Mon-Fri 9.30am-5pm, or email.',
    apply_url: 'https://contact.org.uk/help-for-families/information-advice-services/our-helpline/',
    apply_phone: '0808 808 3555',
  },
  {
    id: 'cdc-resources',
    category: 'education',
    type: 'other',
    conditionCategory: 'all',
    title: 'Council for Disabled Children',
    organisation: 'Council for Disabled Children',
    description: 'The umbrella body for disabled children\'s services across education, health and social care. Their website has excellent plain-English guides on SEND law, EHCPs, transitions to adult services, and your rights. A trusted starting point for understanding the system.',
    eligibility_summary: 'Families, professionals, and anyone supporting disabled children and young people.',
    how_to_apply: 'Browse their free resources online, or contact for more information.',
    apply_url: 'https://councilfordisabledchildren.org.uk/resources',
    apply_phone: '020 7843 6000',
  },
  {
    id: 'sossen-advice',
    category: 'education',
    type: 'helpline',
    conditionCategory: 'all',
    title: 'SOS!SEN \u2014 SEN Education Helpline',
    organisation: 'SOS!SEN',
    description: 'Free, volunteer-run helpline offering practical advice on all aspects of special educational needs. They can help with EHCPs, school placement disputes, exclusions, and understanding your child\'s legal entitlements. Friendly, plain-speaking, and parent-focused.',
    eligibility_summary: 'Parents and carers of children with SEN anywhere in England.',
    how_to_apply: 'Call during term time, or book a 1:1 session for more complex cases. Check their website for current opening hours.',
    apply_url: 'https://sossen.org.uk/services/helpline/',
    apply_phone: '020 8538 3731',
  },

  // === CROSS-CUTTING FINANCIAL ===
  {
    id: 'contact-grants',
    category: 'financial',
    type: 'grant',
    conditionCategory: 'all',
    title: 'Contact \u2014 Grants & Financial Help',
    organisation: 'Contact',
    description: 'Contact maintains a database of grants and financial support available to families with disabled children. Their advisers can help you find funding for essentials like equipment, holidays, clothing, and household items from a wide range of charitable trusts.',
    eligibility_summary: 'Families with a disabled child from birth to age 25 on a low income or receiving benefits.',
    how_to_apply: 'Call the helpline to discuss your situation, or search the grants database on the website.',
    apply_url: 'https://contact.org.uk/',
    apply_phone: '0808 808 3555',
  },
  {
    id: 'turn2us-calculator',
    category: 'financial',
    type: 'other',
    conditionCategory: 'all',
    title: 'Turn2us Benefits Calculator',
    organisation: 'Turn2us',
    description: 'Free, anonymous online tool that checks which benefits you could be claiming. Takes about 20 minutes to complete and shows you exactly what you may be entitled to, including benefits many families don\'t know about. Also has a grants search to find charitable funding.',
    eligibility_summary: 'Anyone living in the UK who wants to check their benefits entitlement.',
    how_to_apply: 'Use the free calculator online. No personal details stored. You can also search for charitable grants.',
    apply_url: 'https://benefits-calculator.turn2us.org.uk/',
  },
];
