// Phase 1: Hardcoded resources for demo/MVP
// Phase 2: Replace with Supabase queries

export const DEMO_RESOURCES = [
  // === FINANCIAL ===
  {
    id: 'dla-children',
    category: 'financial',
    type: 'benefit',
    conditionCategory: 'all',
    title: 'Disability Living Allowance (DLA) for Children',
    organisation: 'Department for Work and Pensions',
    description: 'Tax-free benefit for children under 16 with a health condition or disability. Worth up to \u00A3187.45/week at the highest rate. Special fast-track rules for terminal illness.',
    eligibility_summary: 'Children under 16 who need more help or supervision than a child of the same age without a disability.',
    max_award_gbp: 9748,
    how_to_apply: 'Call the DLA helpline on 0800 121 4600 or download the form from gov.uk. Ask your hospital social worker for help completing it \u2014 they do this regularly.',
    apply_url: 'https://www.gov.uk/disability-living-allowance-children',
    apply_phone: '0800 121 4600',
    turnaround_days: 40,
  },
  {
    id: 'carers-allowance',
    category: 'financial',
    type: 'benefit',
    conditionCategory: 'all',
    title: "Carer's Allowance",
    organisation: 'Department for Work and Pensions',
    description: "\u00A381.90/week for anyone spending 35+ hours a week caring for a child who gets middle or highest rate DLA care component. You don't need to be related to the child.",
    eligibility_summary: "You care for someone 35+ hours/week, earn under \u00A3151/week (after deductions), and you're 16 or over.",
    max_award_gbp: 4259,
    how_to_apply: "Apply online at gov.uk. You'll need your National Insurance number and the child's DLA reference number.",
    apply_url: 'https://www.gov.uk/carers-allowance',
    apply_phone: '0800 731 0297',
    turnaround_days: 28,
  },
  {
    id: 'family-fund',
    category: 'financial',
    type: 'grant',
    conditionCategory: 'all',
    title: 'Family Fund Grant',
    organisation: 'Family Fund',
    description: 'Grants for essential items: washing machines, computers, hospital visiting costs, family breaks, clothing, and bedding. For families on low incomes raising a disabled or seriously ill child.',
    eligibility_summary: 'Families in the UK with a severely disabled or seriously ill child (under 18), on a low income or receiving certain benefits.',
    max_award_gbp: 2000,
    how_to_apply: "Apply online. You'll need a letter from your child's consultant confirming the diagnosis.",
    apply_url: 'https://www.familyfund.org.uk/apply',
    apply_phone: '01904 550055',
    turnaround_days: 42,
  },
  {
    id: 'react-charity',
    category: 'financial',
    type: 'emergency_fund',
    conditionCategory: 'all',
    title: 'REACT Emergency Grants',
    organisation: 'REACT (Rapid Effective Assistance for Children with Potentially Terminal Illness)',
    description: 'Emergency grants for specialist equipment, domestic appliances, educational equipment, holidays, and funeral expenses. Responds within 48 hours.',
    eligibility_summary: 'Children with a life-limiting illness in financially disadvantaged households.',
    how_to_apply: 'Referral required from a health professional, social worker, or charity. They can call or email on your behalf.',
    apply_url: 'https://reactcharity.org/apply',
    apply_phone: '020 8940 2575',
    turnaround_days: 2,
  },
  {
    id: 'ylvc-grant',
    category: 'financial',
    type: 'grant',
    conditionCategory: 'cancer',
    title: 'Young Lives vs Cancer Financial Support',
    organisation: 'Young Lives vs Cancer',
    description: 'Registration grants (\u00A3100), crisis grants, and ongoing financial support for families of children and young people (0-25) with cancer. Also provides free accommodation near treatment centres.',
    eligibility_summary: 'Families of children/young people aged 0-25 diagnosed with cancer in the UK.',
    max_award_gbp: 500,
    how_to_apply: 'Contact their support team. A social worker at your treatment centre can also refer you.',
    apply_url: 'https://www.younglivesvscancer.org.uk/what-we-do/the-six-ways-we-help/',
    apply_phone: '0800 012 1020',
    turnaround_days: 7,
  },
  {
    id: 'htcs',
    category: 'financial',
    type: 'benefit',
    conditionCategory: 'all',
    title: 'Healthcare Travel Costs Scheme',
    organisation: 'NHS',
    description: "Get your travel costs to hospital refunded if you're on a low income or receiving qualifying benefits. Covers public transport, mileage, parking, and sometimes taxis.",
    eligibility_summary: 'Patients/families on qualifying benefits (UC, Income Support, ESA) or low income. Must have a referral for specialist care.',
    how_to_apply: "Claim at the hospital cashier's office after each appointment. Keep all receipts. Claim within 3 months.",
    apply_url: 'https://www.nhs.uk/nhs-services/help-with-health-costs/healthcare-travel-costs-scheme-htcs/',
    turnaround_days: 1,
  },

  // === MEDICAL ===
  {
    id: 'cclg-ptc',
    category: 'medical',
    type: 'hospital',
    conditionCategory: 'cancer',
    title: 'Find Your Principal Treatment Centre',
    organisation: "Children's Cancer and Leukaemia Group (CCLG)",
    description: "The UK has 19 Principal Treatment Centres (PTCs) that specialise in children's cancer. Your child will be referred to the nearest one. They coordinate all treatment including shared care with your local hospital.",
    eligibility_summary: 'All children diagnosed with cancer are referred to their regional PTC.',
    how_to_apply: 'Your GP or local hospital will refer you. If you need to check which PTC covers your area, call CCLG.',
    apply_url: 'https://www.cclg.org.uk/young-people-and-cancer/i-have-cancer/hospitals/principal-treatment-centres',
    apply_phone: '0116 252 5858',
  },
  {
    id: 'chf-specialist',
    category: 'medical',
    type: 'specialist_service',
    conditionCategory: 'heart',
    title: "Children's Heart Federation Support",
    organisation: "Children's Heart Federation",
    description: 'Information and support for families of children with heart conditions. Can help you understand your child\'s diagnosis, treatment options, and connect you with other families.',
    eligibility_summary: 'Any family with a child with a congenital or acquired heart condition.',
    how_to_apply: 'Contact their helpline or browse their condition-specific information pages.',
    apply_url: 'https://www.chfed.org.uk/',
    apply_phone: '0808 808 5000',
  },

  // === EMOTIONAL ===
  {
    id: 'together-helpline',
    category: 'emotional',
    type: 'helpline',
    conditionCategory: 'all',
    title: 'Together for Short Lives Helpline',
    organisation: 'Together for Short Lives',
    description: 'Free helpline for families of children with life-limiting or life-threatening conditions. Can help you find local services, support groups, and answer questions about your rights and entitlements.',
    eligibility_summary: 'Any family with a child (0-18) with a life-limiting or life-threatening condition.',
    how_to_apply: 'Call the helpline. Open Monday to Friday, 9am-5pm.',
    apply_phone: '0808 8088 100',
    apply_url: 'https://www.togetherforshortlives.org.uk/get-support/',
  },
  {
    id: 'rainbow-trust',
    category: 'emotional',
    type: 'support_group',
    conditionCategory: 'all',
    title: 'Rainbow Trust Family Support Workers',
    organisation: 'Rainbow Trust Children\'s Charity',
    description: 'A dedicated Family Support Worker provides ongoing practical and emotional support. They can accompany you to hospital appointments, look after siblings, and be there when you need someone.',
    eligibility_summary: 'Families with a child aged 0-18 with a life-threatening or terminal illness, in areas where Rainbow Trust operates (9 teams across UK).',
    how_to_apply: 'Self-refer via their website or ask your hospital social worker to refer you.',
    apply_url: 'https://www.rainbowtrust.org.uk/support',
    apply_phone: '01372 220000',
  },
  {
    id: 'macmillan-line',
    category: 'emotional',
    type: 'helpline',
    conditionCategory: 'cancer',
    title: 'Macmillan Support Line',
    organisation: 'Macmillan Cancer Support',
    description: 'Free, confidential support from cancer specialists. They can help with medical questions, emotional support, financial guidance, and practical concerns. Open 7 days a week.',
    eligibility_summary: 'Anyone affected by cancer, including parents of children with cancer.',
    how_to_apply: 'Call or use the online chat. No referral needed.',
    apply_phone: '0808 808 0000',
    apply_url: 'https://www.macmillan.org.uk/cancer-information-and-support/get-help',
  },
  {
    id: 'sibs-support',
    category: 'emotional',
    type: 'support_group',
    conditionCategory: 'all',
    title: 'Sibs \u2014 Support for Siblings',
    organisation: 'Sibs',
    description: "Support specifically for brothers and sisters of seriously ill children. Online groups, information, and workshops to help siblings cope with their feelings and experiences.",
    eligibility_summary: 'Siblings of any age whose brother or sister has a disability, chronic illness, or life-limiting condition.',
    apply_url: 'https://www.sibs.org.uk/',
  },

  // === PRACTICAL ===
  {
    id: 'rmh',
    category: 'practical',
    type: 'accommodation',
    conditionCategory: 'all',
    title: 'Ronald McDonald House \u2014 Free Accommodation',
    organisation: 'Ronald McDonald House Charities UK',
    description: "14 free Houses near major children's hospitals across the UK. Families stay for free while their child is in hospital. Includes kitchen, laundry, and play areas. The Alder Hey House has 84 bedrooms.",
    eligibility_summary: 'Families with a child being treated at a partnered NHS hospital. Referral from the hospital is usually needed.',
    how_to_apply: "Ask your child's ward nurse or hospital social worker to refer you. Some Houses accept self-referral.",
    apply_url: 'https://rmhc.org.uk/our-houses/',
    apply_phone: '020 7462 4800',
  },
  {
    id: 'make-a-wish',
    category: 'practical',
    type: 'other',
    conditionCategory: 'all',
    title: 'Make-A-Wish UK',
    organisation: 'Make-A-Wish UK',
    description: "Grants wishes for children aged 3-17 with life-threatening conditions. Wishes can be anything: meeting a hero, going on a trip, having a bedroom makeover, or getting a special experience.",
    eligibility_summary: 'Children aged 3-17 with a life-threatening condition. Medical referral required.',
    how_to_apply: "Referral from a medical professional (consultant, clinical nurse specialist, or social worker). They'll confirm the child's eligibility.",
    apply_url: 'https://www.make-a-wish.org.uk/refer-a-child/',
    apply_phone: '01276 405060',
  },
  {
    id: 'starlight',
    category: 'practical',
    type: 'other',
    conditionCategory: 'all',
    title: 'Starlight Children\u2019s Foundation',
    organisation: "Starlight Children's Foundation",
    description: 'Provides entertainment and play equipment to hospitals, grants wishes for seriously ill children, and offers sensory toys and Distraction Boxes for hospital stays.',
    eligibility_summary: 'Seriously ill children aged 4-18. Wish referral from a medical professional.',
    apply_url: 'https://www.starlight.org.uk/',
    apply_phone: '020 7262 2881',
  },
  {
    id: 'wellchild',
    category: 'practical',
    type: 'other',
    conditionCategory: 'all',
    title: 'WellChild Support',
    organisation: 'WellChild',
    description: 'WellChild Nurses provide support at home, helping coordinate care and reducing hospital visits. They also offer home and garden transformations for families with seriously ill children.',
    eligibility_summary: 'Children with serious or complex health conditions across the UK.',
    apply_url: 'https://www.wellchild.org.uk/',
    apply_phone: '01242 530007',
  },
];
