// Phase 1: Hardcoded resources for demo/MVP
// Phase 2: Replace with Supabase queries

export const DEMO_RESOURCES = [
  // === FINANCIAL ===
  {
    id: 'dla-children',
    category: 'financial',
    type: 'benefit',
    conditionCategory: 'all',
    title: 'Disability Living Allowance (DLA) for Children',
    organisation: 'Department for Work and Pensions',
    description: 'Tax-free benefit for children under 16 with a health condition or disability. The amount depends on your child\'s needs — most families receive middle rate care (around £73.90/week). Higher rates are available for children needing more intensive care or supervision.',
    eligibility_summary: 'Children under 16 who need more help or supervision than a child of the same age without a disability. Based on needs, not diagnosis.',
    max_award_gbp: null,
    how_to_apply: 'Call the DLA helpline on 0800 121 4600 or download the form from gov.uk. Ask your hospital social worker for help completing it \u2014 they do this regularly.',
    apply_url: 'https://www.gov.uk/disability-living-allowance-children',
    apply_phone: '0800 121 4600',
    turnaround_days: 40,
    last_verified: '2026-03',
  },
  {
    id: 'carers-allowance',
    category: 'financial',
    type: 'benefit',
    conditionCategory: 'all',
    title: "Carer's Allowance",
    organisation: 'Department for Work and Pensions',
    description: "\u00A383.30/week for anyone spending 35+ hours a week caring for a child who gets middle or highest rate DLA care component. You must already have DLA awarded before you can apply. You don't need to be related to the child.",
    eligibility_summary: "Your child must be getting DLA (middle or highest rate care). You care for them 35+ hours/week and earn under \u00A3196/week (after deductions).",
    max_award_gbp: 4332,
    how_to_apply: "Apply online at gov.uk. You'll need your National Insurance number and the child's DLA reference number.",
    apply_url: 'https://www.gov.uk/carers-allowance',
    apply_phone: '0800 731 0297',
    turnaround_days: 28,
    last_verified: '2026-03',
  },
  {
    id: 'family-fund',
    category: 'financial',
    type: 'grant',
    conditionCategory: 'all',
    title: 'Family Fund Grant',
    organisation: 'Family Fund',
    description: 'Grants for essential items: washing machines, computers, hospital visiting costs, family breaks, clothing, and bedding. For families on low incomes raising a disabled or seriously ill child.',
    eligibility_summary: 'Families in the UK with a severely disabled or seriously ill child (under 18), on a low income or receiving certain benefits.',
    max_award_gbp: 2000,
    how_to_apply: "Apply online. You'll need a letter from your child's consultant confirming the diagnosis.",
    apply_url: 'https://www.familyfund.org.uk/apply',
    apply_phone: '01904 550055',
    turnaround_days: 42,
    last_verified: '2026-03',
  },
  {
    id: 'react-charity',
    category: 'financial',
    type: 'emergency_fund',
    conditionCategory: 'all',
    title: 'REACT Emergency Grants',
    organisation: 'REACT (Rapid Effective Assistance for Children with Potentially Terminal Illness)',
    description: 'Emergency grants for specialist equipment, domestic appliances, educational equipment, holidays, and funeral expenses. Responds within 48 hours.',
    eligibility_summary: 'Children with a life-limiting illness in financially disadvantaged households.',
    max_award_gbp: 500,
    how_to_apply: 'Referral required from a health professional, social worker, or charity. They can call or email on your behalf.',
    apply_url: 'https://reactcharity.org/apply',
    apply_phone: '020 8940 2575',
    turnaround_days: 2,
    last_verified: '2026-03',
  },
  {
    id: 'ylvc-grant',
    category: 'financial',
    type: 'grant',
    conditionCategory: 'cancer',
    title: 'Young Lives vs Cancer Financial Support',
    organisation: 'Young Lives vs Cancer',
    description: 'Registration grants (\u00A3100), crisis grants, and ongoing financial support for families of children and young people (0-25) with cancer. Also provides free accommodation near treatment centres.',
    eligibility_summary: 'Families of children/young people aged 0-25 diagnosed with cancer in the UK.',
    max_award_gbp: 500,
    how_to_apply: 'Contact their support team. A social worker at your treatment centre can also refer you.',
    apply_url: 'https://www.younglivesvscancer.org.uk/what-we-do/the-six-ways-we-help/',
    apply_phone: '0800 012 1020',
    turnaround_days: 7,
    last_verified: '2026-03',
  },
  {
    id: 'htcs',
    category: 'financial',
    type: 'benefit',
    conditionCategory: 'all',
    title: 'Healthcare Travel Costs Scheme',
    organisation: 'NHS',
    description: "Get your travel costs to hospital refunded if you're on a low income or receiving qualifying benefits. Covers public transport, mileage, parking, and sometimes taxis.",
    eligibility_summary: 'Patients/families on qualifying benefits (UC, Income Support, ESA) or low income. Must have a referral for specialist care.',
    how_to_apply: "Claim at the hospital cashier's office after each appointment. Keep all receipts. Claim within 3 months.",
    apply_url: 'https://www.nhs.uk/nhs-services/help-with-health-costs/healthcare-travel-costs-scheme-htcs/',
    apply_phone: '0300 330 1343', // NHS Business Services Authority helpline
    turnaround_days: 1,
    last_verified: '2026-03',
  },

  // === MEDICAL ===
  {
    id: 'cclg-ptc',
    category: 'medical',
    type: 'hospital',
    conditionCategory: 'cancer',
    title: 'Find Your Principal Treatment Centre',
    organisation: "Children's Cancer and Leukaemia Group (CCLG)",
    description: "The UK has 19 Principal Treatment Centres (PTCs) that specialise in children's cancer. Your child will be referred to the nearest one. They coordinate all treatment including shared care with your local hospital.",
    eligibility_summary: 'All children diagnosed with cancer are referred to their regional PTC.',
    how_to_apply: 'Your GP or local hospital will refer you. If you need to check which PTC covers your area, call CCLG.',
    apply_url: 'https://www.cclg.org.uk/young-people-and-cancer/i-have-cancer/hospitals/principal-treatment-centres',
    apply_phone: '0116 252 5858',
    last_verified: '2026-03',
  },
  {
    id: 'chf-specialist',
    category: 'medical',
    type: 'specialist_service',
    conditionCategory: 'heart',
    title: "Children's Heart Federation Support",
    organisation: "Children's Heart Federation",
    description: 'Information and support for families of children with heart conditions. Can help you understand your child\'s diagnosis, treatment options, and connect you with other families.',
    eligibility_summary: 'Any family with a child with a congenital or acquired heart condition.',
    how_to_apply: 'Contact their helpline or browse their condition-specific information pages.',
    apply_url: 'https://www.chfed.org.uk/',
    apply_phone: '0808 808 5000',
    last_verified: '2026-03',
  },

  // === EMOTIONAL ===
  {
    id: 'together-helpline',
    category: 'emotional',
    type: 'helpline',
    conditionCategory: 'all',
    title: 'Together for Short Lives Helpline',
    organisation: 'Together for Short Lives',
    description: 'Free helpline for families of children with life-limiting or life-threatening conditions. Can help you find local services, support groups, and answer questions about your rights and entitlements.',
    eligibility_summary: 'Any family with a child (0-18) with a life-limiting or life-threatening condition.',
    how_to_apply: 'Call the helpline. Open Monday to Friday, 9am-5pm.',
    apply_phone: '0808 8088 100',
    apply_url: 'https://www.togetherforshortlives.org.uk/get-support/',
    last_verified: '2026-03',
  },
  {
    id: 'rainbow-trust',
    category: 'emotional',
    type: 'support_group',
    conditionCategory: 'all',
    title: 'Rainbow Trust Family Support Workers',
    organisation: 'Rainbow Trust Children\'s Charity',
    description: 'A dedicated Family Support Worker provides ongoing practical and emotional support. They can accompany you to hospital appointments, look after siblings, and be there when you need someone.',
    eligibility_summary: 'Families with a child aged 0-18 with a life-threatening or terminal illness, in areas where Rainbow Trust operates (9 teams across UK).',
    how_to_apply: 'Self-refer via their website or ask your hospital social worker to refer you.',
    apply_url: 'https://www.rainbowtrust.org.uk/support',
    apply_phone: '01372 220000',
    turnaround_days: 14,
    last_verified: '2026-03',
  },
  {
    id: 'macmillan-line',
    category: 'emotional',
    type: 'helpline',
    conditionCategory: 'cancer',
    title: 'Macmillan Support Line',
    organisation: 'Macmillan Cancer Support',
    description: 'Free, confidential support from cancer specialists. They can help with medical questions, emotional support, financial guidance, and practical concerns. Open 7 days a week.',
    eligibility_summary: 'Anyone affected by cancer, including parents of children with cancer.',
    how_to_apply: 'Call or use the online chat. No referral needed.',
    apply_phone: '0808 808 0000',
    apply_url: 'https://www.macmillan.org.uk/cancer-information-and-support/get-help',
    last_verified: '2026-03',
  },
  {
    id: 'sibs-support',
    category: 'emotional',
    type: 'support_group',
    conditionCategory: 'all',
    title: 'Sibs \u2014 Support for Siblings',
    organisation: 'Sibs',
    description: "Support specifically for brothers and sisters of seriously ill children. Online groups, information, and workshops to help siblings cope with their feelings and experiences.",
    eligibility_summary: 'Siblings of any age whose brother or sister has a disability, chronic illness, or life-limiting condition.',
    how_to_apply: 'Visit the website to access online support groups, workshops, and information resources. No referral needed.',
    apply_url: 'https://www.sibs.org.uk/',
    apply_phone: '01535 645453',
    last_verified: '2026-03',
  },

  // === PRACTICAL ===
  {
    id: 'rmh',
    category: 'practical',
    type: 'accommodation',
    conditionCategory: 'all',
    title: 'Ronald McDonald House \u2014 Free Accommodation',
    organisation: 'Ronald McDonald House Charities UK',
    description: "14 free Houses near major children's hospitals across the UK. Families stay for free while their child is in hospital. Includes kitchen, laundry, and play areas. The Alder Hey House has 84 bedrooms.",
    eligibility_summary: 'Families with a child being treated at a partnered NHS hospital. Referral from the hospital is usually needed.',
    how_to_apply: "Ask your child's ward nurse or hospital social worker to refer you. Some Houses accept self-referral.",
    apply_url: 'https://rmhc.org.uk/our-houses/',
    apply_phone: '020 7462 4800',
    last_verified: '2026-03',
  },
  {
    id: 'make-a-wish',
    category: 'practical',
    type: 'other',
    conditionCategory: 'all',
    title: 'Make-A-Wish UK',
    organisation: 'Make-A-Wish UK',
    description: "Grants wishes for children aged 3-17 with life-threatening conditions. Wishes can be anything: meeting a hero, going on a trip, having a bedroom makeover, or getting a special experience.",
    eligibility_summary: 'Children aged 3-17 with a life-threatening condition. Medical referral required.',
    how_to_apply: "Referral from a medical professional (consultant, clinical nurse specialist, or social worker). They'll confirm the child's eligibility.",
    apply_url: 'https://www.make-a-wish.org.uk/refer-a-child/',
    apply_phone: '01276 405060',
    turnaround_days: 90,
    last_verified: '2026-03',
  },
  {
    id: 'starlight',
    category: 'practical',
    type: 'other',
    conditionCategory: 'all',
    title: 'Starlight Children\u2019s Foundation',
    organisation: "Starlight Children's Foundation",
    description: 'Provides entertainment and play equipment to hospitals, grants wishes for seriously ill children, and offers sensory toys and Distraction Boxes for hospital stays.',
    eligibility_summary: 'Seriously ill children aged 4-18. Wish referral from a medical professional.',
    apply_url: 'https://www.starlight.org.uk/',
    apply_phone: '020 7262 2881',
    turnaround_days: 60,
    last_verified: '2026-03',
  },
  {
    id: 'wellchild',
    category: 'practical',
    type: 'other',
    conditionCategory: 'all',
    title: 'WellChild Support',
    organisation: 'WellChild',
    description: 'WellChild Nurses provide support at home, helping coordinate care and reducing hospital visits. They also offer home and garden transformations for families with seriously ill children.',
    eligibility_summary: 'Children with serious or complex health conditions across the UK.',
    how_to_apply: 'Contact WellChild via phone or website to discuss your needs and find out about services in your area.',
    apply_url: 'https://www.wellchild.org.uk/',
    apply_phone: '01242 530007',
    last_verified: '2026-03',
  },

  // === MENTAL HEALTH ===
  {
    id: 'youngminds-helpline',
    category: 'emotional',
    type: 'helpline',
    conditionCategory: 'mental_health',
    title: 'YoungMinds Parents Helpline',
    organisation: 'YoungMinds',
    description: 'Free, confidential helpline for parents worried about their child\'s mental health. Trained advisers can talk through your concerns and help you work out the best next steps, whether your child is struggling with anxiety, self-harm, bullying, or anything else.',
    eligibility_summary: 'Any parent or carer of a child or young person up to age 25.',
    how_to_apply: 'Call the helpline or use the online chat. No referral needed. Open Mon, Thu, Fri 9.30am-4pm and Tue, Wed 9.30am-6pm.',
    apply_url: 'https://www.youngminds.org.uk/parent/parents-helpline/',
    apply_phone: '0808 802 5544',
    last_verified: '2026-03',
  },
  {
    id: 'camhs-referral',
    category: 'medical',
    type: 'specialist_service',
    conditionCategory: 'mental_health',
    title: 'CAMHS \u2014 How to Get a Referral',
    organisation: 'NHS',
    description: 'CAMHS (Child and Adolescent Mental Health Services) is the NHS service for children and young people struggling with their mental health. Referrals can come from your GP, school, or in many areas you can self-refer. Waiting times vary by area.',
    eligibility_summary: 'Children and young people up to age 18 with mental health difficulties that need specialist support.',
    how_to_apply: 'Ask your GP for a referral, or check your local CAMHS website to see if they accept self-referrals. Your child\'s school can also refer.',
    apply_url: 'https://www.nhs.uk/mental-health/nhs-voluntary-charity-services/nhs-services/children-young-people-mental-health-services-cypmhs/',
    apply_phone: '111', // NHS 111 can direct to local CAMHS
    last_verified: '2026-03',
  },
  {
    id: 'kooth-counselling',
    category: 'emotional',
    type: 'helpline',
    conditionCategory: 'mental_health',
    title: 'Kooth Online Counselling',
    organisation: 'Kooth',
    description: 'Free, anonymous online counselling and emotional wellbeing support for young people aged 10-25. No referral or waiting list. Your child can chat with a qualified counsellor via text, join moderated forums, or use self-help tools, all from their phone or laptop.',
    eligibility_summary: 'Young people aged 10-25. Free and anonymous, no GP referral needed.',
    how_to_apply: 'Your child can sign up at kooth.com using just a nickname. No personal details needed. Available every day of the year.',
    apply_url: 'https://www.kooth.com/',
    last_verified: '2026-03',
  },
  {
    id: 'place2be',
    category: 'emotional',
    type: 'support_group',
    conditionCategory: 'mental_health',
    title: 'Place2Be School Counselling',
    organisation: 'Place2Be',
    description: 'Place2Be provides in-school counselling and mental health support in over 500 primary and secondary schools across England, Scotland and Wales. Children can drop in for a chat or be referred for one-to-one counselling by their teacher.',
    eligibility_summary: 'Children at schools that partner with Place2Be. Check their website to see if your school is covered.',
    how_to_apply: 'Ask your child\'s school if they work with Place2Be, or visit the website to find out which schools are partnered.',
    apply_url: 'https://www.place2be.org.uk/our-services/',
    apply_phone: '020 7923 5500',
    last_verified: '2026-03',
  },
  {
    id: 'childline',
    category: 'emotional',
    type: 'helpline',
    conditionCategory: 'mental_health',
    title: 'Childline \u2014 Free Counselling for Under-19s',
    organisation: 'Childline (NSPCC)',
    description: 'Free, confidential helpline for children and young people under 19. Trained counsellors are available 24/7 by phone, online chat, and email. They can help with anything from mental health worries and bullying to abuse and family problems.',
    eligibility_summary: 'Any child or young person under 19 in the UK. Completely free, confidential, and anonymous.',
    how_to_apply: 'Call 0800 1111 any time, day or night. Or start an online chat at childline.org.uk. No referral needed.',
    apply_url: 'https://www.childline.org.uk/',
    apply_phone: '0800 1111',
    last_verified: '2026-03',
  },
  {
    id: 'anna-freud',
    category: 'emotional',
    type: 'information',
    conditionCategory: 'mental_health',
    title: 'Anna Freud Centre \u2014 Family Mental Health Support',
    organisation: 'Anna Freud National Centre for Children and Families',
    description: 'World-leading children\'s mental health charity offering evidence-based resources and support for families. Their website has practical tools for parents, including the Early Years Wellbeing Hub and advice on supporting your child through anxiety, low mood, and difficult experiences.',
    eligibility_summary: 'Any family wanting to support their child\'s mental health. Free resources available to all.',
    how_to_apply: 'Browse free resources and toolkits on the website. For clinical services, referrals come through local NHS services.',
    apply_url: 'https://www.annafreud.org/parents-and-carers/',
    apply_phone: '020 7794 2313',
    last_verified: '2026-03',
  },
  {
    id: 'minded-elearning',
    category: 'education',
    type: 'information',
    conditionCategory: 'mental_health',
    title: 'MindEd \u2014 Free Children\'s Mental Health E-Learning',
    organisation: 'MindEd / Health Education England',
    description: 'Free e-learning resource to help adults identify and support children and young people with mental health difficulties. Covers topics including anxiety, self-harm, eating disorders, ADHD, and autism. Trusted by schools and health professionals, and equally useful for parents.',
    eligibility_summary: 'Free for anyone \u2014 parents, carers, teachers, and professionals. No registration required for many modules.',
    how_to_apply: 'Visit the website and start learning immediately. Self-paced modules you can complete at any time.',
    apply_url: 'https://www.minded.org.uk/',
    last_verified: '2026-03',
  },

  // === DEVELOPMENTAL / AUTISM ===
  {
    id: 'nas-helpline',
    category: 'emotional',
    type: 'helpline',
    conditionCategory: 'developmental',
    title: 'National Autistic Society Helpline',
    conditions: ['autism', 'asd', 'asperger', 'autistic'],
    organisation: 'National Autistic Society',
    description: 'Free helpline for autistic people, their families, and anyone who works with them. They can help you understand a diagnosis, find local services, navigate school issues, or just talk through what you\'re going through.',
    eligibility_summary: 'Anyone affected by autism, including parents awaiting or following a diagnosis.',
    how_to_apply: 'Call the helpline Mon-Thu 10am-4pm, Fri 9am-3pm. No referral needed.',
    apply_url: 'https://www.autism.org.uk/advice-and-guidance/help-and-support',
    apply_phone: '0808 800 4104',
    last_verified: '2026-03',
  },
  {
    id: 'ambitious-autism',
    category: 'practical',
    type: 'other',
    conditionCategory: 'developmental',
    title: 'Ambitious About Autism',
    conditions: ['autism', 'asd', 'autistic'],
    organisation: 'Ambitious about Autism',
    description: 'National charity offering education, support and advocacy for autistic children and young people. They run specialist schools, an online youth network, and campaigns for better understanding and support for autistic young people.',
    eligibility_summary: 'Autistic children and young people and their families across the UK.',
    how_to_apply: 'Visit their website for resources, or call to find out about schools and programmes.',
    apply_url: 'https://www.ambitiousaboutautism.org.uk/',
    apply_phone: '020 8815 5444',
    last_verified: '2026-03',
  },
  {
    id: 'adhd-uk',
    category: 'emotional',
    type: 'support_group',
    conditionCategory: 'developmental',
    title: 'ADHD UK',
    conditions: ['adhd', 'attention deficit', 'add', 'hyperactivity'],
    organisation: 'ADHD UK',
    description: 'National ADHD charity offering information, peer support groups, workplace resources, and practical guides for families. Free tools for managing ADHD at home and school, plus a directory of local support.',
    eligibility_summary: 'Anyone affected by ADHD — parents, carers, adults, and young people.',
    how_to_apply: 'Visit the website for free resources, support groups, and information.',
    apply_url: 'https://adhduk.co.uk/',
    apply_phone: null,
    last_verified: '2026-03',
  },
  {
    id: 'cerebra-services',
    category: 'practical',
    type: 'support_service',
    conditionCategory: 'developmental',
    title: 'Cerebra Free Services',
    organisation: 'Cerebra',
    description: 'Cerebra offers free services for families of children with brain conditions: a specialist sleep advice service, a lending library of sensory toys and equipment, legal rights guidance, and custom equipment design. All services are free — they do not give cash grants.',
    eligibility_summary: 'Children aged 0-16 with a brain-related condition including ADHD, autism, epilepsy, and genetic conditions.',
    how_to_apply: 'Call to discuss which free services could help your family.',
    apply_url: 'https://cerebra.org.uk/what-we-do/',
    apply_phone: '01267 244200',
    last_verified: '2026-03',
  },
  {
    id: 'portage-home',
    category: 'education',
    type: 'specialist_service',
    conditionCategory: 'developmental',
    title: 'National Portage Association \u2014 Home Learning Support',
    organisation: 'National Portage Association',
    description: 'Portage is a home-visiting educational service for pre-school children with additional needs and their families. Trained Portage workers visit your home regularly to help your child develop through play, and show you practical activities you can do every day to support their development.',
    eligibility_summary: 'Pre-school children with developmental delays, disabilities, or additional needs. Referral usually from health visitor or paediatrician.',
    how_to_apply: 'Ask your health visitor, paediatrician, or local authority about the Portage service in your area.',
    apply_url: 'https://www.portage.org.uk/',
    apply_phone: '0121 244 1807',
    last_verified: '2026-03',
  },

  // === SENSORY / COMMUNICATION ===
  {
    id: 'smira-support',
    category: 'emotional',
    type: 'support_group',
    conditionCategory: 'sensory',
    title: 'SMIRA \u2014 Selective Mutism Support',
    conditions: ['selective mutism', 'mutism'],
    organisation: 'Selective Mutism Information & Research Association',
    description: 'The UK\'s leading charity for selective mutism, supporting families since 1992. They offer parent support groups, free downloadable resources, and practical guidance on helping your child communicate. A lifeline if your child speaks freely at home but goes silent in other settings.',
    eligibility_summary: 'Anyone affected by selective mutism, including parents, young people, and professionals.',
    how_to_apply: 'Visit the website for resources and information, or call the helpline.',
    apply_url: 'https://www.selectivemutism.org.uk/',
    apply_phone: '0800 228 9765',
    last_verified: '2026-03',
  },
  {
    id: 'speech-language-uk',
    category: 'medical',
    type: 'specialist_service',
    conditionCategory: 'sensory',
    title: 'I CAN / Speech and Language UK',
    conditions: ['speech', 'language', 'communication'],
    organisation: 'I CAN (now Speech and Language UK)',
    description: 'Free enquiry service where you can speak directly to a speech and language therapist by phone or video call. They help parents understand speech and language delays, offer practical tips, and point you towards local services and support.',
    eligibility_summary: 'Any parent or carer concerned about a child\'s speech, language or communication development.',
    how_to_apply: 'Call the enquiry line or email to book a free call with a speech and language therapist.',
    apply_url: 'https://www.icancharity.org.uk/i-can-help/',
    apply_phone: '020 7843 2544',
    last_verified: '2026-03',
  },
  {
    id: 'ndcs-support',
    category: 'practical',
    type: 'other',
    conditionCategory: 'sensory',
    title: 'National Deaf Children\'s Society (NDCS)',
    conditions: ['deaf', 'hearing'],
    organisation: 'National Deaf Children\'s Society',
    description: 'Free, impartial support for families with deaf children. Their helpline offers guidance on everything from hearing aids and cochlear implants to education rights and benefits. They also run family events and have a technology test centre where you can try equipment.',
    eligibility_summary: 'Any family with a deaf child or young person, from newborn to 18.',
    how_to_apply: 'Call the freephone helpline Mon-Thu 9am-5pm, Fri 9am-12.30pm. No referral needed.',
    apply_url: 'https://www.ndcs.org.uk/',
    apply_phone: '0808 800 8880',
    last_verified: '2026-03',
  },
  {
    id: 'rnib-children',
    category: 'practical',
    type: 'other',
    conditionCategory: 'sensory',
    title: 'RNIB Children\'s Services',
    conditions: ['blind', 'sight', 'visual'],
    organisation: 'RNIB (Royal National Institute of Blind People)',
    description: 'Support for families with blind and partially sighted children, including early years development advice, education support, technology guidance, and emotional support. Their helpline team can help with practical questions about daily life, school, and benefits.',
    eligibility_summary: 'Families with a child or young person with any level of sight loss.',
    how_to_apply: 'Call the helpline or visit the website. No referral needed.',
    apply_url: 'https://www.rnib.org.uk/',
    apply_phone: '0303 123 9999',
    last_verified: '2026-03',
  },
  {
    id: 'sense-deafblind',
    category: 'practical',
    type: 'charity',
    conditionCategory: 'sensory',
    title: 'Sense \u2014 Deafblind and Complex Disability Support',
    conditions: ['deafblind', 'deaf', 'blind'],
    organisation: 'Sense',
    description: 'The UK\'s leading charity for people who are deafblind or have complex disabilities. They provide specialist support from early years onwards, including family advisory services, short breaks, and help accessing education and social activities. Their team understands the unique challenges of dual sensory loss.',
    eligibility_summary: 'Children and adults who are deafblind or have complex communication needs, and their families.',
    how_to_apply: 'Call the helpline or complete the online enquiry form. A family adviser can visit you at home.',
    apply_url: 'https://www.sense.org.uk/',
    apply_phone: '0300 330 9256',
    last_verified: '2026-03',
  },
  {
    id: 'batod-network',
    category: 'education',
    type: 'information',
    conditionCategory: 'sensory',
    title: 'BATOD \u2014 Teachers of the Deaf Support Network',
    conditions: ['deaf', 'hearing'],
    organisation: 'British Association of Teachers of the Deaf',
    description: 'Professional network that can help you find qualified Teachers of the Deaf in your area and understand your child\'s right to specialist education support. Useful if you want to check your child is receiving appropriate support at school or need advice on deaf-friendly teaching approaches.',
    eligibility_summary: 'Parents of deaf children and professionals working with them across the UK.',
    how_to_apply: 'Visit the website to find local Teachers of the Deaf and access resources for families.',
    apply_url: 'https://www.batod.org.uk/',
    last_verified: '2026-03',
  },

  // === LEARNING ===
  {
    id: 'bda-helpline',
    category: 'education',
    type: 'helpline',
    conditionCategory: 'learning',
    title: 'British Dyslexia Association Helpline',
    conditions: ['dyslexia', 'dyscalculia', 'reading'],
    organisation: 'British Dyslexia Association',
    description: 'Free, confidential helpline for anyone affected by dyslexia or dyscalculia. They can advise on getting an assessment, school support, workplace adjustments, and what to do if your child is struggling with reading or writing.',
    eligibility_summary: 'Anyone affected by dyslexia or dyscalculia in the UK, including parents and young people.',
    how_to_apply: 'Call the helpline (Tue 10am-1pm, Wed-Thu 1pm-3pm) or email. Free and confidential.',
    apply_url: 'https://www.bdadyslexia.org.uk/services/helpline',
    apply_phone: '0333 405 4567',
    last_verified: '2026-03',
  },
  {
    id: 'mencap-helpline',
    category: 'practical',
    type: 'helpline',
    conditionCategory: 'learning',
    title: 'Mencap Learning Disability Helpline',
    conditions: ['learning disability', 'intellectual'],
    organisation: 'Mencap',
    description: 'Free advice service for people with a learning disability and their families. They can help with education, benefits, housing, social care, and your rights. If you\'re not sure where to start or what your child is entitled to, Mencap is a good first call.',
    eligibility_summary: 'People with a learning disability and their families or carers across the UK.',
    how_to_apply: 'Call the freephone helpline Mon-Fri 9am-3pm, or email for a response within 5 working days.',
    apply_url: 'https://www.mencap.org.uk/advice-and-support/learning-disability-helpline',
    apply_phone: '0808 808 1111',
    last_verified: '2026-03',
  },
  {
    id: 'dyslexia-action',
    category: 'education',
    type: 'specialist_service',
    conditionCategory: 'learning',
    title: 'Dyslexia Action \u2014 Assessment & Specialist Teaching',
    conditions: ['dyslexia', 'dyscalculia'],
    organisation: 'Dyslexia Action',
    description: 'Offers diagnostic assessments for dyslexia, dyscalculia, and other specific learning difficulties, plus specialist one-to-one teaching and online courses. Their assessments are widely accepted by schools, universities, and exam boards for access arrangements.',
    eligibility_summary: 'Children and adults who need a formal dyslexia assessment or specialist tuition. Fees apply for assessments.',
    how_to_apply: 'Book an assessment online or call to discuss your needs. Assessments can be carried out in person or online.',
    apply_url: 'https://dyslexiaaction.org.uk/',
    apply_phone: '0330 159 8022',
    last_verified: '2026-03',
  },
  {
    id: 'downs-syndrome-learning',
    category: 'education',
    type: 'information',
    conditionCategory: 'learning',
    title: 'Down Syndrome Education International',
    conditions: ['down', 'trisomy 21'],
    organisation: 'Down Syndrome Education International',
    description: 'Research-based resources to support the learning and development of children with Down syndrome. Free online information on reading, language, number skills, and inclusive education, plus practical tips that parents and teachers can use right away.',
    eligibility_summary: 'Parents, carers, and educators supporting children with Down syndrome worldwide.',
    how_to_apply: 'Browse free resources online. Online courses and specialist publications also available.',
    apply_url: 'https://www.dseinternational.org/',
    last_verified: '2026-03',
  },
  {
    id: 'nasen-sen',
    category: 'education',
    type: 'information',
    conditionCategory: 'learning',
    title: 'nasen \u2014 Special Educational Needs Resources',
    organisation: 'nasen (National Association for Special Educational Needs)',
    description: 'The leading membership organisation for SEN professionals, offering practical resources, training, and guidance that parents can also access. Their free resources explain different types of SEN and how schools should be supporting your child.',
    eligibility_summary: 'Parents, teachers, and SENCOs across the UK. Many resources are free; some require membership.',
    how_to_apply: 'Browse the free resources on their website. Schools can join as members for full access.',
    apply_url: 'https://nasen.org.uk/',
    last_verified: '2026-03',
  },

  // === PHYSICAL ===
  {
    id: 'whizz-kidz',
    category: 'practical',
    type: 'other',
    conditionCategory: 'physical',
    title: 'Whizz-Kidz \u2014 Mobility Equipment for Children',
    organisation: 'Whizz-Kidz',
    description: 'The UK\'s leading charity for young wheelchair users. They provide custom wheelchairs and mobility equipment when the NHS can\'t, plus wheelchair skills training, youth clubs, and an employability programme to build independence and confidence.',
    eligibility_summary: 'Young wheelchair users up to age 25 with a permanent physical disability. Equipment applications may have a waiting list.',
    how_to_apply: 'Apply online through the website. A clinical assessment will determine the right equipment for your child.',
    apply_url: 'https://www.whizz-kidz.org.uk/apply/',
    apply_phone: '020 7233 6600',
    turnaround_days: 56,
    last_verified: '2026-03',
  },
  {
    id: 'scope-helpline',
    category: 'emotional',
    type: 'helpline',
    conditionCategory: 'physical',
    title: 'Scope Helpline',
    organisation: 'Scope',
    description: 'Free, independent advice for disabled people and their families. Scope can help with benefits, education, employment, and everyday challenges. Their advisers understand the system and can help you access what you\'re entitled to.',
    eligibility_summary: 'Any disabled person or family member across the UK.',
    how_to_apply: 'Call the freephone helpline Mon-Sat 8am-8pm, Sun 10am-6pm. No referral needed.',
    apply_url: 'https://www.scope.org.uk/helpline',
    apply_phone: '0808 800 3333',
    last_verified: '2026-03',
  },
  {
    id: 'newlife-equipment',
    category: 'financial',
    type: 'grant',
    conditionCategory: 'physical',
    title: 'Newlife Foundation \u2014 Equipment Grants',
    organisation: 'Newlife the Charity for Disabled Children',
    description: 'Provides essential specialist equipment for disabled and terminally ill children when statutory services cannot help or cannot help quickly enough. Their Emergency Equipment Loans can get vital kit to your home within 72 hours while you wait for longer-term provision.',
    eligibility_summary: 'Disabled or terminally ill children under 19 in the UK. Applications must be supported by a health professional.',
    max_award_gbp: 500,
    how_to_apply: 'A health professional (physiotherapist, OT, or similar) must apply on your child\'s behalf. Ask your child\'s therapist to contact Newlife.',
    apply_url: 'https://www.newlifecharity.co.uk/equipment-grants/',
    apply_phone: '0800 902 0095',
    turnaround_days: 21,
    last_verified: '2026-03',
  },
  {
    id: 'mobility-trust',
    category: 'financial',
    type: 'grant',
    conditionCategory: 'physical',
    title: 'Mobility Trust \u2014 Wheelchair Accessible Vehicle Grants',
    organisation: 'Mobility Trust',
    description: 'Helps families with disabled children access wheelchair accessible vehicles. They can provide grants towards the cost of vehicle adaptations or wheelchair accessible vehicles, making it possible to travel together as a family.',
    eligibility_summary: 'Families with a disabled child who needs a wheelchair accessible vehicle and cannot afford the full cost.',
    how_to_apply: 'Contact Mobility Trust to discuss your situation. You will need to provide details of your child\'s mobility needs and financial circumstances.',
    apply_url: 'https://www.mobilitytrust.org.uk/',
    apply_phone: '0300 456 4567',
    turnaround_days: 42,
    last_verified: '2026-03',
  },
  {
    id: 'steps-charity',
    category: 'emotional',
    type: 'support_group',
    conditionCategory: 'physical',
    title: 'Steps \u2014 Lower Limb Conditions in Children',
    conditions: ['clubfoot', 'hip dysplasia', 'limb'],
    organisation: 'Steps Charity Worldwide',
    description: 'Support for families of children born with lower limb conditions including clubfoot, hip dysplasia, and leg length differences. They offer a parent helpline, connect you with other families, and provide clear information on treatment options and what to expect.',
    eligibility_summary: 'Families of children with lower limb conditions including clubfoot, DDH, and other orthopaedic conditions.',
    how_to_apply: 'Call the helpline or visit the website for resources and to connect with other families.',
    apply_url: 'https://www.steps-charity.org.uk/',
    apply_phone: '01925 750271',
    last_verified: '2026-03',
  },

  // === CHRONIC ===
  {
    id: 'diabetes-uk',
    category: 'emotional',
    type: 'helpline',
    conditionCategory: 'chronic',
    title: 'Diabetes UK Family Support',
    conditions: ['diabetes'],
    organisation: 'Diabetes UK',
    description: 'Helpline staffed by trained advisers who understand the daily reality of managing a child\'s diabetes. They can answer medical questions, help with school management plans, connect you with local family groups, and offer emotional support for the whole family.',
    eligibility_summary: 'Anyone affected by diabetes, including parents of children with Type 1 or Type 2 diabetes.',
    how_to_apply: 'Call the helpline Mon-Fri 9am-6pm or email. No referral needed.',
    apply_url: 'https://www.diabetes.org.uk/support-for-you',
    apply_phone: '0345 123 2399',
    last_verified: '2026-03',
  },
  {
    id: 'asthma-lung-uk',
    category: 'medical',
    type: 'helpline',
    conditionCategory: 'chronic',
    title: 'Asthma + Lung UK Helpline',
    conditions: ['asthma', 'lung', 'breathing'],
    organisation: 'Asthma + Lung UK',
    description: 'Speak to a respiratory nurse for free, confidential advice about your child\'s asthma or lung condition. They can help with medication questions, asthma action plans, managing triggers, and what to do in an emergency.',
    eligibility_summary: 'Anyone with a lung condition or their family, including parents of children with asthma.',
    how_to_apply: 'Call Mon-Fri 9am-5pm, or WhatsApp on 07378 606 728. You can also email for a response within 2 working days.',
    apply_url: 'https://www.asthmaandlung.org.uk/helpline',
    apply_phone: '0300 222 5800',
    last_verified: '2026-03',
  },
  {
    id: 'crohns-colitis-uk',
    category: 'emotional',
    type: 'helpline',
    conditionCategory: 'chronic',
    title: "Crohn's & Colitis UK Helpline",
    conditions: ['crohn', 'colitis', 'ibd'],
    organisation: "Crohn's & Colitis UK",
    description: 'Support and information for anyone affected by Crohn\'s disease or ulcerative colitis. Their helpline team can explain treatments, help with school or work accommodations, and connect you with others going through the same thing.',
    eligibility_summary: 'Anyone affected by Crohn\'s disease, ulcerative colitis, or other forms of IBD, including parents.',
    how_to_apply: 'Call Mon-Fri 10am-3pm, use live chat on the website, or email.',
    apply_url: 'https://www.crohnsandcolitis.org.uk/info-support/support-for-you/helpline-service',
    apply_phone: '0300 222 5700',
    last_verified: '2026-03',
  },
  {
    id: 'cystic-fibrosis-trust',
    category: 'emotional',
    type: 'helpline',
    conditionCategory: 'chronic',
    title: 'Cystic Fibrosis Trust Helpline',
    conditions: ['cystic fibrosis', 'cf'],
    organisation: 'Cystic Fibrosis Trust',
    description: 'Free, confidential support for anyone affected by cystic fibrosis. Their helpline team can help with medical questions, emotional support, benefits advice, and practical concerns about managing CF day to day. They also offer grants for essential items.',
    eligibility_summary: 'Anyone affected by cystic fibrosis, including parents and family members.',
    how_to_apply: 'Call the helpline Mon-Fri 9am-5pm or email. No referral needed.',
    apply_url: 'https://www.cysticfibrosis.org.uk/support',
    apply_phone: '0300 373 1000',
    last_verified: '2026-03',
  },
  {
    id: 'jdrf-type1',
    category: 'emotional',
    type: 'support_group',
    conditionCategory: 'chronic',
    title: 'JDRF \u2014 Type 1 Diabetes Support',
    conditions: ['diabetes', 'type 1', 't1d'],
    organisation: 'JDRF (Juvenile Diabetes Research Foundation)',
    description: 'Specialist support for families affected by Type 1 diabetes. They offer a peer support programme connecting newly diagnosed families with experienced Type 1 families, local support groups, and up-to-date information on the latest treatments and technology.',
    eligibility_summary: 'Anyone affected by Type 1 diabetes, including parents of children recently diagnosed.',
    how_to_apply: 'Visit the website to find local support groups or request a peer support match.',
    apply_url: 'https://jdrf.org.uk/',
    apply_phone: '020 7713 2030',
    last_verified: '2026-03',
  },

  // === EDUCATION / SEN ===
  {
    id: 'ipsea-advice',
    category: 'education',
    type: 'advocacy',
    conditionCategory: 'all',
    title: 'IPSEA \u2014 Free SEN Legal Advice',
    organisation: 'IPSEA (Independent Provider of Special Education Advice)',
    description: 'Free, independent legal advice on special educational needs. IPSEA can help you understand your child\'s rights, challenge decisions about EHCP provision, and prepare for SEND Tribunal appeals. Run by legal experts who know the system inside out.',
    eligibility_summary: 'Any parent or carer of a child or young person with SEN or a disability in England.',
    how_to_apply: 'Book a callback on the website, or call the helpline on Tue, Wed, or Fri 9.30am-2.30pm.',
    apply_url: 'https://www.ipsea.org.uk/advice-line',
    apply_phone: '0300 018 4016',
    last_verified: '2026-03',
  },
  {
    id: 'contact-ehcp',
    category: 'education',
    type: 'helpline',
    conditionCategory: 'all',
    title: 'Contact \u2014 EHCP & SEN Advice',
    organisation: 'Contact',
    description: 'Free helpline for families of disabled children covering everything from EHCP applications to benefits, social care, and education rights. If you\'re feeling overwhelmed by paperwork and processes, Contact can talk you through your options step by step.',
    eligibility_summary: 'Parents and carers of disabled children from birth to age 25 across the UK.',
    how_to_apply: 'Call the freephone helpline Mon-Fri 9.30am-5pm, or email.',
    apply_url: 'https://contact.org.uk/help-for-families/information-advice-services/our-helpline/',
    apply_phone: '0808 808 3555',
    last_verified: '2026-03',
  },
  {
    id: 'cdc-resources',
    category: 'education',
    type: 'information',
    conditionCategory: 'all',
    title: 'Council for Disabled Children',
    organisation: 'Council for Disabled Children',
    description: 'The umbrella body for disabled children\'s services across education, health and social care. Their website has excellent plain-English guides on SEND law, EHCPs, transitions to adult services, and your rights. A trusted starting point for understanding the system.',
    eligibility_summary: 'Families, professionals, and anyone supporting disabled children and young people.',
    how_to_apply: 'Browse their free resources online, or contact for more information.',
    apply_url: 'https://councilfordisabledchildren.org.uk/resources',
    apply_phone: '020 7843 6000',
    last_verified: '2026-03',
  },
  {
    id: 'sossen-advice',
    category: 'education',
    type: 'helpline',
    conditionCategory: 'all',
    title: 'SOS!SEN \u2014 SEN Education Helpline',
    organisation: 'SOS!SEN',
    description: 'Free, volunteer-run helpline offering practical advice on all aspects of special educational needs. They can help with EHCPs, school placement disputes, exclusions, and understanding your child\'s legal entitlements. Friendly, plain-speaking, and parent-focused.',
    eligibility_summary: 'Parents and carers of children with SEN anywhere in England.',
    how_to_apply: 'Call during term time, or book a 1:1 session for more complex cases. Check their website for current opening hours.',
    apply_url: 'https://sossen.org.uk/services/helpline/',
    apply_phone: '020 8538 3731',
    last_verified: '2026-03',
  },
  {
    id: 'sendiass',
    category: 'education',
    type: 'advocacy',
    conditionCategory: 'all',
    title: 'SENDIASS \u2014 Free Local SEN Advice',
    organisation: 'SENDIASS (Special Educational Needs and Disabilities Information Advice and Support Services)',
    description: 'Every local authority in England must provide a free, impartial SENDIASS service. They offer confidential advice on SEN processes, help with EHCP applications and reviews, can attend meetings with you, and support you through disagreements with schools or the local authority.',
    eligibility_summary: 'Any parent or young person (0-25) with SEN or a disability in England. Each local authority has its own service.',
    how_to_apply: 'Search for your local SENDIASS on the Council for Disabled Children website, or ask your child\'s school for contact details.',
    apply_url: 'https://councilfordisabledchildren.org.uk/information-advice-and-support-services-network/find-your-local-iass',
    last_verified: '2026-03',
  },

  // === CROSS-CUTTING FINANCIAL ===
  {
    id: 'contact-grants',
    category: 'financial',
    type: 'grant',
    conditionCategory: 'all',
    title: 'Contact \u2014 Grants & Financial Help',
    organisation: 'Contact',
    description: 'Contact maintains a database of grants and financial support available to families with disabled children. Their advisers can help you find funding for essentials like equipment, holidays, clothing, and household items from a wide range of charitable trusts.',
    eligibility_summary: 'Families with a disabled child from birth to age 25 on a low income or receiving benefits.',
    how_to_apply: 'Call the helpline to discuss your situation, or search the grants database on the website.',
    apply_url: 'https://contact.org.uk/',
    apply_phone: '0808 808 3555',
    turnaround_days: 14,
    last_verified: '2026-03',
  },
  {
    id: 'turn2us-calculator',
    category: 'financial',
    type: 'information',
    conditionCategory: 'all',
    title: 'Turn2us Benefits Calculator',
    organisation: 'Turn2us',
    description: 'Free, anonymous online tool that checks which benefits you could be claiming. Takes about 20 minutes to complete and shows you exactly what you may be entitled to, including benefits many families don\'t know about. Also has a grants search to find charitable funding.',
    eligibility_summary: 'Anyone living in the UK who wants to check their benefits entitlement.',
    how_to_apply: 'Use the free calculator online. No personal details stored. You can also search for charitable grants.',
    apply_url: 'https://benefits-calculator.turn2us.org.uk/',
    apply_phone: '0808 802 2000',
    last_verified: '2026-03',
  },

  // === NEUROLOGICAL ===
  {
    id: 'epilepsy-action',
    category: 'emotional',
    type: 'helpline',
    conditionCategory: 'neurological',
    title: 'Epilepsy Action Helpline',
    conditions: ['epilepsy', 'seizure', 'fits'],
    organisation: 'Epilepsy Action',
    description: 'Free, confidential helpline for anyone affected by epilepsy. Their trained advisers can help with understanding seizures, medication questions, school support, benefits, and the emotional impact of epilepsy on the whole family. They also offer small grants for essential items.',
    eligibility_summary: 'Anyone affected by epilepsy in the UK, including parents of children with epilepsy.',
    how_to_apply: 'Call the helpline Mon-Fri 8.30am-5pm, use live chat, or email.',
    apply_url: 'https://www.epilepsy.org.uk/info/support',
    apply_phone: '0808 800 5050',
    last_verified: '2026-03',
  },
  {
    id: 'epilepsy-action-grants',
    category: 'financial',
    type: 'grant',
    conditionCategory: 'neurological',
    title: 'Epilepsy Action \u2014 Sapphire Nurses & Grants',
    conditions: ['epilepsy', 'seizure'],
    organisation: 'Epilepsy Action',
    description: 'Epilepsy Action provides small grants for people with epilepsy who are in financial hardship, helping with essentials like furniture replacement after seizure damage or safety equipment. Their Sapphire Nurses also provide specialist epilepsy nursing support.',
    eligibility_summary: 'People with epilepsy in the UK who are experiencing financial hardship. Must be receiving means-tested benefits.',
    max_award_gbp: 300,
    how_to_apply: 'Call the helpline to discuss a grant application, or ask your epilepsy nurse to refer you.',
    apply_url: 'https://www.epilepsy.org.uk/info/support/grants',
    apply_phone: '0808 800 5050',
    turnaround_days: 21,
    last_verified: '2026-03',
  },
  {
    id: 'mduk-grants',
    category: 'financial',
    type: 'grant',
    conditionCategory: 'neurological',
    title: 'Muscular Dystrophy UK \u2014 Equipment Grants',
    conditions: ['muscular dystrophy', 'duchenne', 'muscle'],
    organisation: 'Muscular Dystrophy UK',
    description: 'Grants for equipment and adaptations that help children and adults with muscle-wasting conditions live more independently. They can help with specialist wheelchairs, home adaptations, communication aids, and other essential equipment the NHS cannot provide.',
    eligibility_summary: 'People with a muscle-wasting condition in the UK. Priority given to those who cannot access funding from statutory services.',
    max_award_gbp: 2000,
    how_to_apply: 'Apply online through their website or call the care and support line for help with the application.',
    apply_url: 'https://www.musculardystrophyuk.org/support/grants/',
    apply_phone: '0800 652 6352',
    turnaround_days: 28,
    last_verified: '2026-03',
  },
  {
    id: 'cerebral-palsy-cymru',
    category: 'medical',
    type: 'specialist_service',
    conditionCategory: 'neurological',
    title: 'Cerebral Palsy Cymru \u2014 Wales Specialist Therapy',
    conditions: ['cerebral palsy', 'cp'],
    organisation: 'Cerebral Palsy Cymru',
    description: 'Wales-based charity providing specialist therapy, education, and support for children with cerebral palsy and other neurological conditions. Their multidisciplinary team offers physiotherapy, occupational therapy, speech therapy, and specialist education in a family-centred environment.',
    eligibility_summary: 'Children with cerebral palsy and similar neurological conditions in Wales. Referrals from health professionals or self-referral.',
    how_to_apply: 'Self-refer via the website or ask your child\'s paediatrician, GP, or health visitor to refer.',
    apply_url: 'https://www.cerebralpalsycymru.org/',
    apply_phone: '029 2052 2600',
    last_verified: '2026-03',
  },
  {
    id: 'epilepsy-society',
    category: 'medical',
    type: 'information',
    conditionCategory: 'neurological',
    title: 'Epilepsy Society \u2014 Information & Support',
    conditions: ['epilepsy', 'seizure'],
    organisation: 'Epilepsy Society',
    description: 'The UK\'s leading epilepsy medical charity, providing expert information on all types of epilepsy and seizures. Their resources for parents cover everything from first diagnosis through to managing epilepsy at school, first aid for seizures, and understanding medication.',
    eligibility_summary: 'Anyone affected by epilepsy or seeking information about seizures in children.',
    how_to_apply: 'Browse their comprehensive resources online or call the helpline for personalised information.',
    apply_url: 'https://epilepsysociety.org.uk/',
    apply_phone: '01494 601 400',
    last_verified: '2026-03',
  },
  {
    id: 'brain-tumour-charity',
    category: 'emotional',
    type: 'helpline',
    conditionCategory: 'neurological',
    title: 'The Brain Tumour Charity Support Line',
    conditions: ['brain tumour', 'brain tumor'],
    organisation: 'The Brain Tumour Charity',
    description: 'Free support for families affected by brain tumours in children. Their specialist team can help you understand your child\'s diagnosis, navigate treatment options, access benefits and financial support, and connect with other families going through similar experiences.',
    eligibility_summary: 'Anyone affected by a brain tumour, including parents of children with brain tumours.',
    how_to_apply: 'Call the support line Mon-Fri 9am-5pm, email, or use the live chat.',
    apply_url: 'https://www.thebraintumourcharity.org/get-support/',
    apply_phone: '0808 800 0004',
    last_verified: '2026-03',
  },

  // === GENETIC ===
  {
    id: 'genetic-alliance-uk',
    category: 'practical',
    type: 'information',
    conditionCategory: 'genetic',
    title: 'Genetic Alliance UK \u2014 Information & Support',
    organisation: 'Genetic Alliance UK',
    description: 'The national charity for everyone affected by a genetic condition. They can help you understand a genetic diagnosis, find condition-specific support groups, access genetic counselling, and navigate the healthcare system. Their helpline is a good first port of call for newly diagnosed families.',
    eligibility_summary: 'Anyone affected by a genetic condition in the UK, including parents of children with genetic conditions.',
    how_to_apply: 'Call the helpline Mon-Fri 9.30am-5pm or email. They can also help you find a specialist support group for your child\'s specific condition.',
    apply_url: 'https://geneticalliance.org.uk/',
    apply_phone: '020 7831 0883',
    last_verified: '2026-03',
  },
  {
    id: 'unique-rare-chromosome',
    category: 'emotional',
    type: 'support_group',
    conditionCategory: 'genetic',
    title: 'Unique \u2014 Rare Chromosome Disorder Support',
    conditions: ['chromosome', 'gene disorder'],
    organisation: 'Unique (Rare Chromosome Disorder Support Group)',
    description: 'The only charity in the UK dedicated to supporting families affected by rare chromosome disorders. They provide condition-specific information guides, connect you with other families with the same diagnosis, and offer a listening ear when you need it most. Particularly valuable when your child\'s condition is so rare that your doctors have limited experience.',
    eligibility_summary: 'Families affected by rare chromosome or gene disorders worldwide, including undiagnosed conditions.',
    how_to_apply: 'Register on the website to access guides and connect with other families. Free to join.',
    apply_url: 'https://www.rarechromo.org/',
    apply_phone: '01883 723356',
    last_verified: '2026-03',
  },
  {
    id: 'downs-syndrome-association',
    category: 'emotional',
    type: 'helpline',
    conditionCategory: 'genetic',
    title: 'Down\'s Syndrome Association Helpline',
    conditions: ['down', 'trisomy 21'],
    organisation: 'Down\'s Syndrome Association',
    description: 'Free, confidential helpline offering support and information for families of people with Down syndrome. From the first moments after diagnosis through to adulthood, they provide clear, up-to-date information on health, education, and what to expect. Their helpline team includes parents who have been where you are.',
    eligibility_summary: 'Anyone affected by Down syndrome in England, Wales, and Northern Ireland.',
    how_to_apply: 'Call the helpline Mon-Fri 10am-4pm, or email. No referral needed.',
    apply_url: 'https://www.downs-syndrome.org.uk/',
    apply_phone: '0333 1212 300',
    last_verified: '2026-03',
  },
  {
    id: 'syndromes-without-name',
    category: 'emotional',
    type: 'support_group',
    conditionCategory: 'genetic',
    title: 'SWAN UK \u2014 Syndromes Without A Name',
    conditions: ['undiagnosed', 'unknown', 'swan'],
    organisation: 'SWAN UK (Syndromes Without A Name)',
    description: 'Dedicated support for families of children with undiagnosed genetic conditions. When your child doesn\'t fit neatly into a known diagnosis, SWAN UK provides a community of families who understand, plus practical help with navigating services that often require a label to access support.',
    eligibility_summary: 'Families of children with undiagnosed genetic conditions in the UK.',
    how_to_apply: 'Join online for free. Access forums, local meet-ups, and one-to-one support from SWAN UK volunteers.',
    apply_url: 'https://www.undiagnosed.org.uk/',
    apply_phone: '020 7704 3141',
    last_verified: '2026-03',
  },
  {
    id: 'together-genetic',
    category: 'practical',
    type: 'charity',
    conditionCategory: 'genetic',
    title: 'Together for Short Lives \u2014 Genetic Conditions Support',
    organisation: 'Together for Short Lives',
    description: 'Many genetic conditions are life-limiting. Together for Short Lives can help families access children\'s hospice services, palliative care, respite breaks, and sibling support. Their directory helps you find local children\'s hospices and community services.',
    eligibility_summary: 'Families of children with life-limiting genetic conditions in the UK.',
    how_to_apply: 'Call the helpline or search their directory for services near you.',
    apply_url: 'https://www.togetherforshortlives.org.uk/get-support/',
    apply_phone: '0808 8088 100',
    last_verified: '2026-03',
  },

  // === RARE DISEASE ===
  {
    id: 'findacure',
    category: 'practical',
    type: 'information',
    conditionCategory: 'rare',
    title: 'Findacure \u2014 UK Rare Disease Research & Support',
    organisation: 'Findacure',
    description: 'UK-based charity helping patient groups for rare diseases to drive research and improve care. They support families in setting up patient advocacy groups, accessing clinical trials, and connecting with researchers working on their child\'s condition.',
    eligibility_summary: 'UK families affected by rare diseases, and patient advocacy groups wanting to accelerate research.',
    how_to_apply: 'Browse rare disease resources online or contact for help connecting with research and support networks.',
    apply_url: 'https://www.findacure.org.uk/',
    apply_phone: '020 3862 7893',
    last_verified: '2026-03',
  },
  {
    id: 'rare-disease-uk',
    category: 'emotional',
    type: 'support_group',
    conditionCategory: 'rare',
    title: 'Rare Disease UK \u2014 Patient Network',
    organisation: 'Rare Disease UK (part of Genetic Alliance UK)',
    description: 'The national alliance for people with rare diseases and all who support them. They campaign for better rare disease services, connect families with condition-specific groups, and provide a community for those who often feel isolated by the rarity of their child\'s diagnosis.',
    eligibility_summary: 'Anyone affected by a rare disease in the UK.',
    how_to_apply: 'Visit the website for resources and to find condition-specific patient groups.',
    apply_url: 'https://www.raredisease.org.uk/',
    apply_phone: '020 7831 0883',
    last_verified: '2026-03',
  },
  {
    id: 'nihr-rare-diseases',
    category: 'medical',
    type: 'information',
    conditionCategory: 'rare',
    title: 'NIHR BioResource \u2014 Rare Disease Research',
    organisation: 'National Institute for Health and Care Research',
    description: 'The NHS research programme for rare diseases, offering families the chance to participate in cutting-edge research into their child\'s condition. Being part of the BioResource can help advance understanding and treatment of rare diseases, and may give access to new therapies.',
    eligibility_summary: 'Patients with rare diseases in England who are interested in participating in research.',
    how_to_apply: 'Ask your child\'s consultant about the NIHR BioResource, or visit the website to learn more about ongoing studies.',
    apply_url: 'https://bioresource.nihr.ac.uk/',
    last_verified: '2026-03',
  },

  // === BEHAVIOURAL ===
  {
    id: 'challenging-behaviour-foundation',
    category: 'emotional',
    type: 'helpline',
    conditionCategory: 'behavioural',
    title: 'Challenging Behaviour Foundation Helpline',
    organisation: 'Challenging Behaviour Foundation',
    description: 'Free information and support for families caring for children with severe learning disabilities whose behaviour is described as challenging. They understand the isolation and stress families face and offer practical strategies alongside emotional support.',
    eligibility_summary: 'Families of children with severe learning disabilities and challenging behaviour.',
    how_to_apply: 'Call the family support line Mon-Fri 10am-2pm, or email.',
    apply_url: 'https://www.challengingbehaviour.org.uk/',
    apply_phone: '0300 666 0126',
    last_verified: '2026-03',
  },
  {
    id: 'ocd-action',
    category: 'emotional',
    type: 'helpline',
    conditionCategory: 'behavioural',
    title: 'OCD Action Helpline',
    conditions: ['ocd', 'obsessive compulsive'],
    organisation: 'OCD Action',
    description: 'Free support and information for people affected by OCD, including children and their parents. Their helpline can provide advice on getting a diagnosis, accessing treatment (particularly CBT), and managing OCD\'s impact on school and family life.',
    eligibility_summary: 'Anyone affected by OCD in the UK, including parents of children with OCD.',
    how_to_apply: 'Call the helpline Mon-Fri 9.30am-5pm, email, or use the webchat.',
    apply_url: 'https://www.ocdaction.org.uk/',
    apply_phone: '0300 636 5478',
    last_verified: '2026-03',
  },
  {
    id: 'young-minds-crisis',
    category: 'emotional',
    type: 'helpline',
    conditionCategory: 'behavioural',
    title: 'YoungMinds Crisis Messenger',
    organisation: 'YoungMinds',
    description: 'Free 24/7 text-based crisis support for young people experiencing a mental health crisis. If your child is feeling overwhelmed, out of control, or unsafe, they can text for immediate support from a trained volunteer.',
    eligibility_summary: 'Young people in crisis in the UK. Available 24/7.',
    how_to_apply: 'Text YM to 85258 for free, 24/7 support. Your child can also text if they are worried about their behaviour.',
    apply_url: 'https://www.youngminds.org.uk/young-person/find-help/',
    apply_phone: '85258', // text service
    last_verified: '2026-03',
  },
  {
    id: 'pda-society',
    category: 'emotional',
    type: 'support_group',
    conditionCategory: 'behavioural',
    title: 'PDA Society \u2014 Pathological Demand Avoidance Support',
    conditions: ['pda', 'demand avoidance'],
    organisation: 'PDA Society',
    description: 'Support and information for families of children with a PDA profile of autism. PDA can look like extreme defiance or anxiety-driven avoidance, and standard parenting and school strategies often backfire. The PDA Society provides evidence-based guidance that actually works.',
    eligibility_summary: 'Families and professionals supporting children with a PDA profile, anywhere in the UK.',
    how_to_apply: 'Browse their resources online, or join their forum and local groups for peer support.',
    apply_url: 'https://www.pdasociety.org.uk/',
    // apply_phone omitted - PDA Society primarily uses email/web contact; verify if phone line exists
    last_verified: '2026-03',
  },
  {
    id: 'papyrus-prevention',
    category: 'emotional',
    type: 'helpline',
    conditionCategory: 'behavioural',
    title: 'PAPYRUS \u2014 Prevention of Young Suicide',
    organisation: 'PAPYRUS',
    description: 'The UK charity for the prevention of young suicide. Their HOPELINEUK service provides confidential support and practical advice for young people under 35 who are feeling suicidal, and for anyone who is concerned about a young person. Available every day of the year.',
    eligibility_summary: 'Young people under 35 and anyone worried about a young person.',
    how_to_apply: 'Call HOPELINEUK every day 9am-midnight, text 07860 039967, or email.',
    apply_url: 'https://www.papyrus-uk.org/',
    apply_phone: '0800 068 4141',
    last_verified: '2026-03',
  },

  // === CANCER (additional) ===
  {
    id: 'clic-sargent-social',
    category: 'practical',
    type: 'support_group',
    conditionCategory: 'cancer',
    title: 'Young Lives vs Cancer \u2014 Social Workers',
    organisation: 'Young Lives vs Cancer',
    description: 'Specialist social workers based in children\'s cancer treatment centres across the UK. They help families navigate benefits, housing, practical challenges, and emotional support from the moment of diagnosis. They know the system and can advocate on your behalf.',
    eligibility_summary: 'Families of children with cancer being treated at a principal treatment centre.',
    how_to_apply: 'Ask your child\'s treatment team about the Young Lives vs Cancer social worker at your hospital.',
    apply_url: 'https://www.younglivesvscancer.org.uk/',
    apply_phone: '0800 012 1020',
    last_verified: '2026-03',
  },
  {
    id: 'ccrn-info',
    category: 'medical',
    type: 'information',
    conditionCategory: 'cancer',
    title: 'Children\'s Cancer & Leukaemia Group Information',
    organisation: 'CCLG',
    description: 'Clear, reliable information about children\'s cancers written by specialists and reviewed by families. Covers each type of childhood cancer, treatment options, clinical trials, and what to expect. An essential resource when you want to understand your child\'s diagnosis.',
    eligibility_summary: 'Anyone wanting reliable information about children\'s cancer.',
    how_to_apply: 'Browse free information online or order printed booklets.',
    apply_url: 'https://www.cclg.org.uk/',
    apply_phone: '0116 252 5858',
    last_verified: '2026-03',
  },

  // === HEART (additional) ===
  {
    id: 'tiny-tickers',
    category: 'emotional',
    type: 'support_group',
    conditionCategory: 'heart',
    title: 'Tiny Tickers \u2014 Baby Heart Support',
    organisation: 'Tiny Tickers',
    description: 'Support for families of babies with heart conditions, from antenatal diagnosis through the early years. They offer a parent support line, a peer support buddy system connecting you with experienced heart parents, and support packs for newly diagnosed families.',
    eligibility_summary: 'Families of babies and young children with congenital heart conditions.',
    how_to_apply: 'Call the support line or request a support pack through the website.',
    apply_url: 'https://www.tinytickers.org/',
    apply_phone: '0808 196 1504',
    last_verified: '2026-03',
  },
  {
    id: 'bhf-helpline',
    category: 'medical',
    type: 'helpline',
    conditionCategory: 'heart',
    title: 'British Heart Foundation Helpline',
    organisation: 'British Heart Foundation',
    description: 'Specialist cardiac nurses available to answer your questions about heart conditions, treatment, and recovery. They can explain your child\'s diagnosis in plain language, discuss medication and surgical options, and provide reliable, evidence-based information.',
    eligibility_summary: 'Anyone with a heart or circulatory condition, or their family.',
    how_to_apply: 'Call the Heart Helpline Mon-Fri 9am-5pm. No referral needed.',
    apply_url: 'https://www.bhf.org.uk/',
    apply_phone: '0300 330 3311',
    last_verified: '2026-03',
  },
  {
    id: 'lhm-charity',
    category: 'emotional',
    type: 'support_group',
    conditionCategory: 'heart',
    title: 'Little Hearts Matter',
    conditions: ['single ventricle', 'hlhs', 'hypoplastic'],
    organisation: 'Little Hearts Matter',
    description: 'The only UK charity dedicated to supporting families of children with a functionally single ventricle heart. They provide specialist information, a network of families who truly understand, and practical support through every stage from diagnosis to adulthood.',
    eligibility_summary: 'Families of children with a single ventricle heart condition in the UK.',
    how_to_apply: 'Call or email to speak with their family support team. They can connect you with other families.',
    apply_url: 'https://www.lhm.org.uk/',
    apply_phone: '0121 455 8982',
    last_verified: '2026-03',
  },
  {
    id: 'heartline-families',
    category: 'emotional',
    type: 'support_group',
    conditionCategory: 'heart',
    title: 'Heart Line Association \u2014 Family Support',
    organisation: 'Heart Line Association',
    description: 'A national charity offering emotional and practical support to families of children born with heart defects. Run largely by experienced heart parents, they provide peer support, hospital visiting, and a helpline staffed by people who have been through it.',
    eligibility_summary: 'Families of children with congenital heart defects across the UK.',
    how_to_apply: 'Contact via the website or phone to be matched with a parent supporter.',
    apply_url: 'https://heartline.org.uk/',
    apply_phone: '0300 030 8603',
    last_verified: '2026-03',
  },

  // === RESPIRATORY ===
  {
    id: 'asthma-lung-uk-children',
    category: 'medical',
    type: 'information',
    conditionCategory: 'respiratory',
    title: 'Asthma + Lung UK \u2014 Children\'s Asthma Resources',
    conditions: ['asthma'],
    organisation: 'Asthma + Lung UK',
    description: 'Comprehensive information and tools for parents of children with asthma. Includes action plan templates, advice on managing asthma at school, spotting triggers, and what to do in an asthma attack. Their children\'s section is specifically tailored for families.',
    eligibility_summary: 'Parents and carers of children with asthma or other lung conditions.',
    how_to_apply: 'Browse free resources online or call the nurse helpline for personalised advice.',
    apply_url: 'https://www.asthmaandlung.org.uk/conditions/asthma/child/',
    apply_phone: '0300 222 5800',
    last_verified: '2026-03',
  },
  {
    id: 'cf-trust-children',
    category: 'medical',
    type: 'specialist_service',
    conditionCategory: 'respiratory',
    title: 'Cystic Fibrosis Trust \u2014 Children\'s Services',
    conditions: ['cystic fibrosis', 'cf'],
    organisation: 'Cystic Fibrosis Trust',
    description: 'Specialist information and support for families of children with cystic fibrosis. Covers treatment, nutrition, physiotherapy, school life, and emotional wellbeing. Their clinical resources help ensure your child receives the best possible care.',
    eligibility_summary: 'Families of children with cystic fibrosis in the UK.',
    how_to_apply: 'Call the helpline or browse condition-specific resources online.',
    apply_url: 'https://www.cysticfibrosis.org.uk/support',
    apply_phone: '0300 373 1000',
    last_verified: '2026-03',
  },
  {
    id: 'primary-ciliary',
    category: 'emotional',
    type: 'support_group',
    conditionCategory: 'respiratory',
    title: 'PCD Family Support Group',
    conditions: ['pcd', 'ciliary dyskinesia'],
    organisation: 'PCD Family Support Group UK',
    description: 'Support and information for families affected by primary ciliary dyskinesia (PCD), a rare condition affecting the lungs and airways. They connect families going through similar experiences and provide practical information about living with PCD.',
    eligibility_summary: 'Families of children and adults with PCD in the UK.',
    how_to_apply: 'Visit the website to join the support network and access resources.',
    apply_url: 'https://www.pcdsupport.org.uk/',
    last_verified: '2026-03',
  },
  {
    id: 'breathe-easy-blf',
    category: 'emotional',
    type: 'support_group',
    conditionCategory: 'respiratory',
    title: 'Asthma + Lung UK \u2014 Breathe Easy Support Groups',
    organisation: 'Asthma + Lung UK',
    description: 'Network of local support groups for people with lung conditions and their families. Breathe Easy groups meet regularly, offering a chance to share experiences, get practical tips, and feel less alone in managing your child\'s condition.',
    eligibility_summary: 'Anyone affected by a lung condition, including parents of children with respiratory conditions.',
    how_to_apply: 'Find your local Breathe Easy group on the website. Meetings are free to attend.',
    apply_url: 'https://www.asthmaandlung.org.uk/support/breathe-easy',
    apply_phone: '0300 222 5800',
    last_verified: '2026-03',
  },
  {
    id: 'ssa-uk',
    category: 'medical',
    type: 'information',
    conditionCategory: 'respiratory',
    title: 'Sleep Apnoea Trust \u2014 Children\'s Sleep Breathing',
    conditions: ['sleep apnoea', 'sleep apnea', 'sleep'],
    organisation: 'Sleep Apnoea Trust Association',
    description: 'Information and support for families of children with obstructive sleep apnoea and sleep-disordered breathing. They provide practical guidance on recognising symptoms, getting a diagnosis, and the treatment options available for children.',
    eligibility_summary: 'Families of children with sleep apnoea or suspected sleep-disordered breathing.',
    how_to_apply: 'Browse resources online or contact for advice.',
    apply_url: 'https://www.sleep-apnoea-trust.org/',
    apply_phone: '0800 025 3500',
    last_verified: '2026-03',
  },

  // === METABOLIC ===
  {
    id: 'climb-metabolic',
    category: 'emotional',
    type: 'support_group',
    conditionCategory: 'metabolic',
    title: 'Metabolic Support UK (formerly CLIMB)',
    organisation: 'Metabolic Support UK',
    description: 'The UK\'s leading charity for inherited metabolic disorders. They provide condition-specific information, family support services, and connect you with other families managing the same condition. Their specialist team understands the daily complexities of metabolic conditions, from emergency protocols to dietary management.',
    eligibility_summary: 'Anyone affected by an inherited metabolic disorder in the UK.',
    how_to_apply: 'Call the helpline or browse condition-specific information on the website.',
    apply_url: 'https://www.metabolicsupportuk.org/',
    apply_phone: '0800 652 3181',
    last_verified: '2026-03',
  },
  {
    id: 'mps-society',
    category: 'emotional',
    type: 'support_group',
    conditionCategory: 'metabolic',
    title: 'MPS Society \u2014 Mucopolysaccharide & Related Diseases',
    conditions: ['mps', 'mucopolysaccharide', 'fabry'],
    organisation: 'Society for Mucopolysaccharide Diseases',
    description: 'Specialist support for families affected by MPS, Fabry, and related diseases. They offer a dedicated family advocacy service, clinical trial information, grants for equipment, and family conferences where you can meet specialists and other families.',
    eligibility_summary: 'Families of children with MPS, Fabry, or related lysosomal storage diseases in the UK.',
    how_to_apply: 'Call the advocacy team or register online for family support.',
    apply_url: 'https://www.mpssociety.org.uk/',
    apply_phone: '0345 389 9901',
    last_verified: '2026-03',
  },
  {
    id: 'galactosaemia-support',
    category: 'emotional',
    type: 'support_group',
    conditionCategory: 'metabolic',
    title: 'Galactosaemia Support Group',
    conditions: ['galactosaemia', 'galactosemia'],
    organisation: 'Galactosaemia Support Group',
    description: 'Support and information for families managing galactosaemia, a rare metabolic condition detected through newborn screening. They offer practical advice on the galactose-free diet, connect families with each other, and provide clear explanations of the condition.',
    eligibility_summary: 'Families of children with galactosaemia in the UK.',
    how_to_apply: 'Visit the website to join the support network and access dietary guidance.',
    apply_url: 'https://www.galactosaemia.org/',
    last_verified: '2026-03',
  },
  {
    id: 'pku-nspku',
    category: 'practical',
    type: 'support_group',
    conditionCategory: 'metabolic',
    title: 'NSPKU \u2014 Phenylketonuria Support',
    conditions: ['pku', 'phenylketonuria'],
    organisation: 'National Society for Phenylketonuria (NSPKU)',
    description: 'The UK\'s charity for phenylketonuria (PKU), supporting families from newborn diagnosis through to adulthood. They provide dietary advice, recipes, a helpline, and local support groups. Their annual conference is a chance to meet specialists and other PKU families.',
    eligibility_summary: 'Families of children with PKU and adults living with PKU in the UK.',
    how_to_apply: 'Call the helpline or join online for access to resources and local groups.',
    apply_url: 'https://www.nspku.org/',
    apply_phone: '020 8364 3010',
    last_verified: '2026-03',
  },
  {
    id: 'metabolic-dietary',
    category: 'medical',
    type: 'information',
    conditionCategory: 'metabolic',
    title: 'BIMDG \u2014 Metabolic Emergency Protocols',
    organisation: 'British Inherited Metabolic Disease Group',
    description: 'Essential emergency protocols for inherited metabolic diseases. If your child has a metabolic condition, these protocols tell hospital staff exactly what to do in an emergency. Keep a copy in your child\'s hospital bag and share with your local A&E department.',
    eligibility_summary: 'Healthcare professionals and families managing inherited metabolic conditions.',
    how_to_apply: 'Download emergency protocols free from the website. Share with every hospital that may treat your child.',
    apply_url: 'https://bimdg.org.uk/',
    last_verified: '2026-03',
  },
];
